update arch tests for K extension
riscv-non-isa/riscv-arch-test pull request #201
Opened 2021-08-17 13:25 UTC by liweiwei90

- update format for aes32 and sm4 instructions
- update reference signature for sha256 and sm3 instructions in rv64i_m/K_unratified
- delete zip and unzip tests in rv64i_m/K_unratified
- update tests for aes64ks1i, sm4ed and sm4ks to use byte_count with overlap = "Y" to improve the coverage of S-boxes

2021-08-17 13:31 UTC, ben-marshall commented
@liweiwei90 - Thank you for this! Did you talk to IIT before doing this work / did you know they were already working on it?

@neelgala - I thought IIT Madras were working on these?

2021-08-17 14:14 UTC, liweiwei90 commented
Sorry, I didn't talk to IIT before. Our CAS/PLCT lab is the owner of two related task in the development partner(https://docs.google.com/spreadsheets/d/1qzu6b9kgADGjaa5fd1Qla7b9gCMOaEnGO5bUVu2oPys/edit#gid=156613795, line 26 and 27). I asked markku what we really need to do. He replied "_If all S-boxes and all the instruction invocations in a couple of encryptions, decryptions, and key schedules are covered, I think that is sufficient_" (the email was copied to you on Fri, Jul 30). I described the problems of s-boxes coverage I found in current arch tests in the last week meeting. This work is to  fix the problems. I also have sended two related PRs to riscv-ctg(https://github.com/riscv/riscv-ctg/pull/12) and riscv-isac(https://github.com/riscv/riscv-isac/pull/16) before this PR.

> @liweiwei90 - Thank you for this! Did you talk to IIT before doing this work / did you know they were already working on it?
> 
> @neelgala - I thought IIT Madras were working on these?

2021-08-18 10:54 UTC, neelgala commented
Yes IIT has been working on this. I was notified about some issues in isac/ctg regarding these in the last developers meet - which I believe @liweiwei90 has fixed and raised PRs. There are additional changes required in the tests identified by IITM (the "K" in the RVTEST_CASE strings for Zks, Zkn, etc needs to be lower-cased everywhere for compatibility with the riscv-config yaml)

@liweiwei90 The artifacts of this PR were generated using your PRs on ctg and isac ? If so, I will merge those PRs, put in IIT's changes and then regenerate those artifacts. - would that work ?

2021-08-18 12:48 UTC, ben-marshall commented
@liweiwei90 - which toolchain did you use to test this? I tried looking on the PLCT Jenkins server but it doesn't look like the GNU toolchain build is working or includes the latest spec changes?

Otherwise, these look like the changes I'd expect for the new spec updates, so however they get merged I'm happy about it.

2021-08-18 14:18 UTC, liweiwei90 commented
> Yes IIT has been working on this. I was notified about some issues in isac/ctg regarding these in the last developers meet - which I believe @liweiwei90 has fixed and raised PRs. There are additional changes required in the tests identified by IITM (the "K" in the RVTEST_CASE strings for Zks, Zkn, etc needs to be lower-cased everywhere for compatibility with the riscv-config yaml)
> 
> @liweiwei90 The artifacts of this PR were generated using your PRs on ctg and isac ? If so, I will merge those PRs, put in IIT's changes and then regenerate those artifacts. - would that work ?

@neelgala  yes, the *-01 tests are generated by riscv-ctg using the two PRs.  If you try to regenerate these artifacts, two changes should be made:
- Some *-rwp tests should be handwriting modified because of the format of the instructions have changed and they cannot be generated by riscv-ctg.
- Some reference signature should be updated since the function of some instructions have been changed to sign-extended the 32 bits result.

2021-08-18 14:28 UTC, liweiwei90 commented
> @liweiwei90 - which toolchain did you use to test this? I tried looking on the PLCT Jenkins server but it doesn't look like the GNU toolchain build is working or includes the latest spec changes?
> 
> Otherwise, these look like the changes I'd expect for the new spec updates, so however they get merged I'm happy about it.

@ben-marshall  Currently, I used the toolchain build from the riscv-crypto github following the steps described in it. I'll try to add it to our Jenkins server later. 
Since I used the latest version of the toolchain for the new spec, I found some errors when I built the old tests. So the modified tests in this patch are fit for the new spec.

2021-08-18 14:39 UTC, pawks requested changes

2021-08-18 14:39 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +#define TEST_RI_OP(inst, destreg, reg1, reg2, imm, correctval, val1, val2, swreg, offset, testreg) \
Changing the definition for this macro affects the tests already present in the repository. If such a macro is needed, a new macro should be defined and used in the tests.

2021-08-19 02:43 UTC, liweiwei90 commented on riscv-test-suite/env/arch_test.h
> +#define TEST_RI_OP(inst, destreg, reg1, reg2, imm, correctval, val1, val2, swreg, offset, testreg) \
All the instructions using  'TEST_RI_OP'  definition(aes32 and sm4 instructions) in the repo have been changed to the new format. So they should use the new 'TEST_RI_OP'  definition and the old 'TEST_RI_OP' will not be used after this change.

2021-08-20 07:06 UTC, liweiwei90 commented
> > @liweiwei90 - which toolchain did you use to test this? I tried looking on the PLCT Jenkins server but it doesn't look like the GNU toolchain build is working or includes the latest spec changes?
> > Otherwise, these look like the changes I'd expect for the new spec updates, so however they get merged I'm happy about it.
> 
> @ben-marshall Currently, I used the toolchain build from the riscv-crypto github following the steps described in it. I'll try to add it to our Jenkins server later.
> Since I used the latest version of the toolchain for the new spec, I found some errors when I built the old tests. So the modified tests in this patch are fit for the new spec.

@ben-marshall  the result can be found in the Jenkins server now: https://ci.rvperf.org/view/Krypto-Scalar/job/riscv-arch-test-k-extension/

2021-08-20 07:53 UTC, ben-marshall commented
@liweiwei90 - That's great to see it working on your Jenkins server :+1:

2021-10-06 13:18 UTC, ben-marshall commented
*Ping* - what needs to happen to move this forward?

2021-10-14 14:58 UTC, merged