Include files sync up from RISCV-CTG
riscv-non-isa/riscv-arch-test pull request #231
Opened 2022-02-09 10:07 UTC by yungchinghsiao

This pull request attempts to sync up arch_test.h and encoding.h from RISCV-CTG

2022-02-18 16:56 UTC, allenjbaum requested changes
Unless I'm missing some context, this will break every test that isn't a floating point test
SREG is the width of the X registers; it doesn't change just because FLEN changes

2022-02-18 17:14 UTC, allenjbaum requested changes
For RVTEST_SIGUPD_P64: it is clearly the case that this is for an RV32 only. Therefore, you don't need to use SREG.  
And, in one case you  have an explicit offset of 4, and the other you use REGWIDTH. 
And, this doesn't check for offset overflow.
And this completely replicates the RVTEST_SIGUPD_FID macro, so just alias it.
RVTEST_SIGUPD_PK64 doesn't check overflow either, 
And, again you have an explicit offset of 4, but update using REGWIDTH. Be consistant.
And: REGWIDTH+REGWIDTH+REGWIDTH should simply be 3*REGWIDTH (or just be 12 if this can only be used for RV32)

2022-02-18 17:23 UTC, allenjbaum reviewed
TEST_RD_OP completely replicates TEST_CMV_OP. Just alias it

2022-02-18 17:26 UTC, allenjbaum requested changes
Unless I'm missing some context, this will break every test that isn't a floating point test
LREG, SREG is the width of the X registers; it doesn't change just because FLEN changes.
Was this intended to (re)define FSREG, FLREG?

2022-02-18 17:32 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +
@allenjbaum You are right. These lines should be removed. This particular case will be handled explicitly in the F test macros when they are ready. These can be removed.

2022-02-18 17:43 UTC, allenjbaum commented
I would have them in separate PRs (after the macros get fixed).
I have added my requests for changes.

On Fri, Feb 18, 2022 at 12:21 AM S Pawan Kumar ***@***.***>
wrote:

> @allenjbaum <https://github.com/allenjbaum> This PR adds the necessary
> macros for the Pext tests. I think the tests for the P extension can also
> be added to this PR or they can come as another independent PR. What do you
> think?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/231#issuecomment-1044125463>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJWUKEC6RUOKMLAF3N3U3X6RFANCNFSM5N5AIWUQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-21 15:57 UTC, yungchinghsiao commented on riscv-test-suite/env/arch_test.h
> +
I've removed these lines in the new changes in this PR.

2022-02-21 16:02 UTC, yungchinghsiao commented
> For RVTEST_SIGUPD_P64: it is clearly the case that this is for an RV32 only. Therefore, you don't need to use SREG. And, in one case you have an explicit offset of 4, and the other you use REGWIDTH. And, this doesn't check for offset overflow. And this completely replicates the RVTEST_SIGUPD_FID macro, so just alias it. RVTEST_SIGUPD_PK64 doesn't check overflow either, And, again you have an explicit offset of 4, but update using REGWIDTH. Be consistant. And: REGWIDTH+REGWIDTH+REGWIDTH should simply be 3*REGWIDTH (or just be 12 if this can only be used for RV32)

Fixed by making these macros constants. and thanks for this review, I found that TEST_PKRR_OP() and TEST_PKR_OP() should have updated their flagreg to signatures.

2022-02-21 16:02 UTC, yungchinghsiao commented
> TEST_RD_OP completely replicates TEST_CMV_OP. Just alias it

Done

2022-02-21 16:04 UTC, yungchinghsiao commented
Sorry, accidentally closed this pull request. reopening it now.

2022-03-02 05:59 UTC, yungchinghsiao commented
@allenjbaum @pawks: I wonder if you had any chance to look at my changes to address your review comments? Please do not hesitate to let me know if there are anything that I should do further.

2022-03-02 19:58 UTC, pawks commented
I think all the old comments have been addressed and this PR can be merged.

2022-03-03 00:51 UTC, allenjbaum requested changes
These all update offset, but never check that it will cause an overflow.
I have this code at the beginning every SIGUPD macro:
  .if offset+{update_amt} >=2048   ;\
     addi   _BR, _BR,offset                 ;\
     .set   offset, 0				 ;\
  .endif						 ;\

These macros are much longer than they need to be because of the way you check for NARG(__VA_ARGS__) == 0,1. This becomes much more understandable if you instead use this;
  .if NARG(__VA_ARGS__) == 1				       ;\
     .set offset, _ARG1(__VA_OPT__(__VA_ARGS__,0))	;\
  .endif 
and then use offset after that point ( instead of ARG1() )while removing the other code conditional  on __ARG1 (well, remove one, and remove the .if/.endif from the other.)
I think I made a mistake asking for explicit offset and sw instead of SREG if you knew it was for RV32.  I was mostly trying to get consistent use. It's much safer to use REGWIDTH and SREG, as it enables these macros to be reused for the other length, but this code is not broken, so perhaps just leave that alone for now.

As I mentioned, RVTEST_SIGUPD_P64 is redundant and an alias of RVTEST_SIGUPD_FID, can be replaced by:
#define RVTEST_SIGUPD_P64(_BR,_R,_R_HI,...)		 \
 .if NARG(__VA_ARGS__) == 0				;\
	RVTEST_SIGUPD_FID(_BR,_R,_R_HI)			;\
 .else							;\
 	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
 .endif

2022-03-03 06:57 UTC, yungchinghsiao commented
Hello Allen,

I don't fully understand your comment on SIGUPD macros. Are you suggesting
me to do the following updates? If you could confirm this is what you mean,
I could help apply them to all SIGUPD macros (BTW, I thought offset
overflow was handled in generator.py in RISCV-CTG)

*diff --git a/riscv_ctg/env/arch_test.h b/riscv_ctg/env/arch_test.h*

*index a05966b..322de13 100644*

*--- a/riscv_ctg/env/arch_test.h*

*+++ b/riscv_ctg/env/arch_test.h*

@@ -573,14 +573,15 @@ rvtest_data_end:

 #define _ARG1(_1ST,...) _1ST

 #define NARG(...) _ARG5(__VA_OPT__(__VA_ARGS__,)4,3,2,1,0)

 #define RVTEST_SIGUPD(_BR,_R,...)\

+  .if offset+REGWIDTH >=2048;\

+    addi _BR, _BR, offset;\

+    .set offset, 0;\

+  .endif;\

   .if NARG(__VA_ARGS__) == 1;\

-    SREG _R,_ARG1(__VA_ARGS__,0)(_BR);\

-    .set offset,_ARG1(__VA_OPT__(__VA_ARGS__,)0)+REGWIDTH;\

+    .set offset,_ARG1(__VA_OPT__(__VA_ARGS__,)0);\

   .endif;\

-  .if NARG(__VA_ARGS__) == 0;\

-    SREG _R,offset(_BR);\

+  SREG _R,offset(_BR);\

   .set offset,offset+REGWIDTH;\

-  .endif;



 #define RVTEST_SIGUPD_F(_BR,_R,_F,...)\

   .if NARG(__VA_ARGS__) == 1;\





Or the modified macro:



#define RVTEST_SIGUPD(_BR,_R,...)\

  .if offset+REGWIDTH >=2048;\

    addi _BR, _BR, offset;\

    .set offset, 0;\

  .endif;\

  .if NARG(__VA_ARGS__) == 1;\

    .set offset,_ARG1(__VA_OPT__(__VA_ARGS__,)0);\

  .endif;\

  SREG _R,offset(_BR);\

  .set offset,offset+REGWIDTH;\



On Thu, Mar 3, 2022 at 8:51 AM Allen Baum ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> These all update offset, but never check that it will cause an overflow.
> I have this code at the beginning every SIGUPD macro:
> .if offset+{update_amt} >=2048 ;
> addi _BR, _BR,offset ;
> .set offset, 0 ;
> .endif ;\
>
> These macros are much longer than they need to be because of the way you
> check for NARG(*VA_ARGS*) == 0,1. This becomes much more understandable
> if you instead use this;
> .if NARG(*VA_ARGS*) == 1 ;
> .set offset, _ARG1(*VA_OPT*(*VA_ARGS*,0)) ;
> .endif
> and then use offset after that point ( instead of ARG1() )while removing
> the other code conditional on __ARG1 (well, remove one, and remove the
> .if/.endif from the other.)
> I think I made a mistake asking for explicit offset and sw instead of SREG
> if you knew it was for RV32. I was mostly trying to get consistent use.
> It's much safer to use REGWIDTH and SREG, as it enables these macros to be
> reused for the other length, but this code is not broken, so perhaps just
> leave that alone for now.
>
> As I mentioned, RVTEST_SIGUPD_P64 is redundant and an alias of
> RVTEST_SIGUPD_FID, can be replaced by:
> #define RVTEST_SIGUPD_P64(_BR,_R,_R_HI,...)
> .if NARG(*VA_ARGS*) == 0 ;
> RVTEST_SIGUPD_FID(_BR,_R,_R_HI) ;
> .else ;
> RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(*VA_OPT*(*VA_ARGS*,0)));
> .endif
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/231#pullrequestreview-898335470>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEMVK7SHGSIEN7LYDA5QPBLU6AEILANCNFSM5N5AIWUQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-03-04 06:16 UTC, allenjbaum commented
CTG can keep track of it, but no one is required to use CTG, so we need to
make the macros bulletproof.
The code you listed for SIGUPD is what I mean. I modified all the SIGUPD
macros I could find in the file I sent you,
so you should be able to see them all, not just SIGUPD but also SIGUPD_F,
SIGUPD_FID, SIG_UPD_P64, etc.
You should just cut and paste that entire section with SIGUPD*,
[VAL]BASEUPD*, **WITH** all the comments.

On Wed, Mar 2, 2022 at 10:57 PM Yung-Ching Hsiao ***@***.***>
wrote:

> Hello Allen,
>
> I don't fully understand your comment on SIGUPD macros. Are you suggesting
> me to do the following updates? If you could confirm this is what you mean,
> I could help apply them to all SIGUPD macros (BTW, I thought offset
> overflow was handled in generator.py in RISCV-CTG)
>
> *diff --git a/riscv_ctg/env/arch_test.h b/riscv_ctg/env/arch_test.h*
>
> *index a05966b..322de13 100644*
>
> *--- a/riscv_ctg/env/arch_test.h*
>
> *+++ b/riscv_ctg/env/arch_test.h*
>
> @@ -573,14 +573,15 @@ rvtest_data_end:
>
> #define _ARG1(_1ST,...) _1ST
>
> #define NARG(...) _ARG5(__VA_OPT__(__VA_ARGS__,)4,3,2,1,0)
>
> #define RVTEST_SIGUPD(_BR,_R,...)\
>
> + .if offset+REGWIDTH >=2048;\
>
> + addi _BR, _BR, offset;\
>
> + .set offset, 0;\
>
> + .endif;\
>
> .if NARG(__VA_ARGS__) == 1;\
>
> - SREG _R,_ARG1(__VA_ARGS__,0)(_BR);\
>
> - .set offset,_ARG1(__VA_OPT__(__VA_ARGS__,)0)+REGWIDTH;\
>
> + .set offset,_ARG1(__VA_OPT__(__VA_ARGS__,)0);\
>
> .endif;\
>
> - .if NARG(__VA_ARGS__) == 0;\
>
> - SREG _R,offset(_BR);\
>
> + SREG _R,offset(_BR);\
>
> .set offset,offset+REGWIDTH;\
>
> - .endif;
>
>
>
> #define RVTEST_SIGUPD_F(_BR,_R,_F,...)\
>
> .if NARG(__VA_ARGS__) == 1;\
>
>
>
>
>
> Or the modified macro:
>
>
>
> #define RVTEST_SIGUPD(_BR,_R,...)\
>
> .if offset+REGWIDTH >=2048;\
>
> addi _BR, _BR, offset;\
>
> .set offset, 0;\
>
> .endif;\
>
> .if NARG(__VA_ARGS__) == 1;\
>
> .set offset,_ARG1(__VA_OPT__(__VA_ARGS__,)0);\
>
> .endif;\
>
> SREG _R,offset(_BR);\
>
> .set offset,offset+REGWIDTH;\
>
>
>
> On Thu, Mar 3, 2022 at 8:51 AM Allen Baum ***@***.***> wrote:
>
> > ***@***.**** requested changes on this pull request.
> >
> > These all update offset, but never check that it will cause an overflow.
> > I have this code at the beginning every SIGUPD macro:
> > .if offset+{update_amt} >=2048 ;
> > addi _BR, _BR,offset ;
> > .set offset, 0 ;
> > .endif ;\
> >
> > These macros are much longer than they need to be because of the way you
> > check for NARG(*VA_ARGS*) == 0,1. This becomes much more understandable
> > if you instead use this;
> > .if NARG(*VA_ARGS*) == 1 ;
> > .set offset, _ARG1(*VA_OPT*(*VA_ARGS*,0)) ;
> > .endif
> > and then use offset after that point ( instead of ARG1() )while removing
> > the other code conditional on __ARG1 (well, remove one, and remove the
> > .if/.endif from the other.)
> > I think I made a mistake asking for explicit offset and sw instead of
> SREG
> > if you knew it was for RV32. I was mostly trying to get consistent use.
> > It's much safer to use REGWIDTH and SREG, as it enables these macros to
> be
> > reused for the other length, but this code is not broken, so perhaps just
> > leave that alone for now.
> >
> > As I mentioned, RVTEST_SIGUPD_P64 is redundant and an alias of
> > RVTEST_SIGUPD_FID, can be replaced by:
> > #define RVTEST_SIGUPD_P64(_BR,_R,_R_HI,...)
> > .if NARG(*VA_ARGS*) == 0 ;
> > RVTEST_SIGUPD_FID(_BR,_R,_R_HI) ;
> > .else ;
> > RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(*VA_OPT*(*VA_ARGS*,0)));
> > .endif
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/riscv-non-isa/riscv-arch-test/pull/231#pullrequestreview-898335470
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AEMVK7SHGSIEN7LYDA5QPBLU6AEILANCNFSM5N5AIWUQ
> >
> > .
> > Triage notifications on the go with GitHub Mobile for iOS
> > <
> https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675
> >
> > or Android
> > <
> https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub
> >.
> >
> > You are receiving this because you modified the open/close state.Message
> > ID: ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/231#issuecomment-1057734916>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJXMVP5NR3A42IUHXDLU6BPE3ANCNFSM5N5AIWUQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-04 18:38 UTC, yungchinghsiao commented
@allenjbaum I rebased the PR to the latest master and updated all of the  SIGUPD* macros, including the comments. Please check again.

2022-03-04 18:45 UTC, allenjbaum commented
looks good

2022-03-04 18:50 UTC, allenjbaum commented
This addresses all my issues

2022-03-08 20:05 UTC, allenjbaum approved these changes
This addresses all my issues

2022-03-09 06:11 UTC, allenjbaum approved these changes
Thisis exactly what was requested

2022-03-09 12:42 UTC, merged