Test cases for P extension
riscv-non-isa/riscv-arch-test pull request #243
Opened 2022-03-17 14:18 UTC by yungchinghsiao

2022-04-23 00:47 UTC, allenjbaum commented
This isn't going to get much further if merge conficts aren't sorted out...

2022-04-23 18:04 UTC, yungchinghsiao commented
> This isn't going to get much further if merge conficts aren't sorted out...

I've regenerated test patterns using RISCV-CTG 0.6.3 and rebased to the latest master and resolved conflicts.

2022-05-10 13:26 UTC, allenjbaum commented
This seems to be a common issue: the CHANGELOG.md file has a merge issue. It should be easy to fix. I haven't looked at the actual PR yet.

2022-05-10 14:11 UTC, allenjbaum requested changes

2022-05-10 14:11 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
>      .set offset,offset+(3*REGWIDTH)
This is incorrect; The CHK_OFFSET macro is updating the hidden offset variable as it goes along,
so this should be just +REGWIDTH. But, even simpler is to just redefine this in terms of the existing SIGUPD_FID macro:
 #define RVTEST_SIGUPD_P64(_BR,_R,_R_HI,_F,...)		 \
 rdov _F						;\
 .if NARG(__VA_ARGS__) == 0				;\
	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_)		;\
 .else							;\
 	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
 .endif

2022-05-10 15:33 UTC, yungchinghsiao commented on riscv-test-suite/env/arch_test.h
>      .set offset,offset+(3*REGWIDTH)
I resolved the conflict and fixed the macro according to your suggestion. Please take a look.

2022-05-10 15:44 UTC, allenjbaum requested changes

2022-05-10 15:44 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +	RVTEST_SIGUPD_FID(_BR,_R,_R_HI)			;\
oops, my typo, this probably doesn't compile; the _F parameter was left off
  this should be
	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_F)		;\

2022-05-10 15:44 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
oops, my typo, this probably doesn't compile; the _F parameter was left off
this should be RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_F,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\

2022-05-11 15:58 UTC, yungchinghsiao commented on riscv-test-suite/env/arch_test.h
> +	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
@allenjbaum Good catch. However, I do not see how _F as the 4th argument of  RVTEST_SIGUPD_FID() would be saved to the signature memory: RVTEST_SIGUPD_FID() saves just its 2nd and 3rd arguments only. I wonder if the following code would work?

```
#define RVTEST_SIGUPD_PK64(_BR,_R,_R_HI,_F,...)\
 .if NARG(__VA_ARGS__) == 0                             ;\
        RVTEST_SIGUPD_FID(_BR,_R,_R_HI)                 ;\
 .else                                                  ;\
        RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
 .endif                                                 ;\
        CHK_OFFSET(_BR,SIGALIGN,0);                     ;\
        rdov _F                                         ;\
        SREG _F,offset(_BR)                             ;\
        .set offset,offset+(SIGALIGN)
```

2022-05-11 17:35 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
You are correct; I was fooled by the fact that you are storing 2 separate results, as opp[osed to a result and a flag.
Your fix works. Thanks for catching this.

2022-05-11 17:52 UTC, yungchinghsiao commented on riscv-test-suite/env/arch_test.h
> +	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
Committed the change as 16bf67a.

2022-05-12 01:01 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
oops - I just noticed that SIGUPD_FID uses REGWIDTH, so that final .set offset should probably use it as well

2022-05-13 03:18 UTC, yungchinghsiao commented on riscv-test-suite/env/arch_test.h
> +	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
I'm not sure if this is the latest comment or the one after [16bf67a](https://github.com/riscv-non-isa/riscv-arch-test/commit/16bf67aaf817673a1292b1f5da3c07b90a389913) is. I'll assume this one is the latest comment since it looks a valid concern to me.

You are right about SIGALIGN: it is not defined when FLEN is 0. Does this mean we need another version of SIGUPD macro for RVTEST_SIGUPD_PK() RVTEST_SIGUPD_PK64() and RVTEST_SIGUPD_P64()? These macros are expected to be used independent of whether F/D are present so REGWIDTH should be used instead of SIGALIGN in all these macros.

2022-05-13 05:45 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
The correct version should only have REGWIDTH, not SIGALIGN,  and only update offset by a single REGWIDTH, never by n*REGWIDTH (because CHK_OFFSET does intermediate updates) so replace SIGALGN with REGWIDTH in [16bf67a] and it will be correct.

2022-05-13 15:11 UTC, yungchinghsiao commented on riscv-test-suite/env/arch_test.h
> +	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
So shall I expand RVTEST_SIGUPD_FID() before replacing REGWIDTH with SIGALIGN? or just replace the SIGALIGN after "rdov _F" with REGWIDTH for the changes in [https://github.com/riscv-non-isa/riscv-arch-test/commit/16bf67aaf817673a1292b1f5da3c07b90a389913]

2022-05-13 19:02 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
I recommend expanding.The other is shorter, but it's also a bit harder to follow as it's another layer of indirection.  But I just spotted another typo in FID . Only the first instance of CHK_OFFSET should have the last parameter be zero.  IT should look like this:

#define RVTEST_SIGUPD_FID(_BR,_R,_F,...)		 \
  .if NARG(__VA_ARGS__) == 1                            ;\
     .set offset,_ARG1(__VA_ARGS__,0)			;\
  .endif                                                ;\
  CHK_OFFSET(_BR, REGWIDTH, 0)				;\
  SREG _R,offset(_BR)					;\
  CHK_OFFSET(_BR, REGWIDTH, 1)				;\ <-- change
  SREG _F,offset+REGWIDTH(_BR)				;\
  .set offset,offset+REGWIDTH

and then (moving the rdov to the top for readability)
#define RVTEST_SIGUPD_P64(_BR,_R,_R_HI,_F,...)		 \
  rdov _F                                                ;\
  .if NARG(__VA_ARGS__) == 1                            ;\
     .set offset,_ARG1(__VA_ARGS__,0)			;\
  .endif                                                ;\
  CHK_OFFSET(_BR, REGWIDTH, 0)				;\
  SREG _R,offset(_BR)					;\
  CHK_OFFSET(_BR, REGWIDTH, 1)				;\
  SREG _F,offset+REGWIDTH(_BR)				;\
  CHK_OFFSET(_BR, REGWIDTH, 1)				;\
  SREG _F,offset+REGWIDTH(_BR)				;\
  .set offset,offset+REGWIDTH

2022-05-16 05:13 UTC, yungchinghsiao commented on riscv-test-suite/env/arch_test.h
> +	RVTEST_SIGUPD_FID(_BR,_R,_R_HI,_ARG1(__VA_OPT__(__VA_ARGS__,0)));\
@allenjbaum  Please checked my changes in [2f370d1](https://github.com/riscv-non-isa/riscv-arch-test/pull/243/commits/2f370d1932e33bed7257c58c189fadeebdcd2489). I have to also expand TEST_CASE_FID() to avoid it calling RVTEST_SIGUPD_FID() in TEST_PKR_OP().

2022-05-16 16:07 UTC, allenjbaum approved these changes
This looks correct: versions that store:
reg+flag (pk), reg pair (p64), reg pair+flag (p64k) and reg+flag with 1 input (pkr). 
Since these all use only xregs, only REGWIDTH is used. 
The first CHK_OFFSET has a final parameter of 0, the rest use 1.  
Just an observation that sometimes the flag register is the last thing you store, sometimes the first. This is still a correct implementation, but might cause a little confusion to someone reviewing or debugging results.

2022-05-16 16:44 UTC, neelgala commented
@yungchinghsiao since we have migrated to RISCOF the references no longer need to be checked. Please remove them from your PR. Will review it once that is done.

2022-05-17 07:06 UTC, yungchinghsiao commented
@neelgala I removed references, Makefile and Makefrag from the P_unratified directory. I also took the chance to update arch_test.h to make the ordering of updating the _F flag consistent with other macros as noted by @allenjbaum .

2022-06-01 00:37 UTC, yungchinghsiao commented
> @neelgala I removed references, Makefile and Makefrag from the P_unratified directory. I also took the chance to update arch_test.h to make the ordering of updating the _F flag consistent with other macros as noted by @allenjbaum .

@neelgala anything I need to do for this pull request?

2022-10-28 06:26 UTC, merged