Updated arch_test.h file
riscv-non-isa/riscv-arch-test pull request #277
Opened 2022-08-14 12:03 UTC by UmerShahidengr

This PR is co-authored-by: allenjbaum [allen.baum@esperantotech.com](mailto:allen.baum@esperantotech.com), and modification of [PR-267](https://github.com/riscv-non-isa/riscv-arch-test/pull/267).
As requested by @pawks, the trap handler and macro definitions have been split into two different files, arch_test.h contains definitions of trap handler, macros to change privilege modes, and other necessary macros while macros to manage storing signatures, and ops dependent general macros are defined in test_macros.h file.
The major changes with respect to [PR-267](https://github.com/riscv-non-isa/riscv-arch-test/pull/267) are as follows:

- Removed the bugs in RVTEST_GOTO_LOWER_MODE macro
- Removed the bugs in RVTEST_GOTO_MMODE macro and defined strap_routine directive. 
- Updated RVTEST_TRAP_SAVEAREA and RVTEST_TRAP_EPILOG macros to refine the definitions of per mode save area macros.

2022-08-16 07:06 UTC, pawks requested changes

2022-08-16 07:06 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +      li   t4, 1		/* optimize for single bit		*/
Lower case `li` should be avoided.

2022-08-16 07:06 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +	li	t2, 0			// save and clear edeleg so we can exit to Mmode
Lower case `li` should be avoided.

2022-08-16 07:06 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +      li   t4, 1		/* optimize for single bit		*/
The `LI` macro should be used instead.

2022-08-16 07:34 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +	.endif
This version of the fixed length `LA` macro doesn't compile correctly. Multiple errors of the following form occur:
```
jal-01.S:193: Error: non-constant expression in ".if" statement
jal-01.S:193: Error: illegal operands `addi x2,x2,0x0FFF&(5b-.>>8)'
jal-01.S:193: Error: illegal operands `addi x2,x2,REG_SV_OFF'
```
This is mainly due to the unavailability of the addresses at the preprocessing/assembly time. The addresses can be resolved only at linking time and hence manipulating the address values is not feasible as a part of the macros.

2022-08-17 06:16 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +	li	t2, 0			// save and clear edeleg so we can exit to Mmode
It is OK in this case because it is known what immediate it is and it is guaranteed to be a single instruction

2022-08-17 06:16 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +      li   t4, 1		/* optimize for single bit		*/
It is OK in this case because it is known what immediate it is and it is guaranteed to be a single instruction

2022-08-17 09:21 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> +	.endif
The error resolved in the latest commit. The definition of LAU was broken so it has been removed.

2022-09-15 18:29 UTC, UmerShahidengr commented
Hello @pawks, @allenjbaum and I have updated the trap handler, and now it is working perfectly. Please review and merge it

2022-09-20 14:12 UTC, InspireSemi requested changes
In test_macros.h 
The #warnings have been commented out.   Either we uncomment these or just remove the this whole section from the file.  Lines 768 - 818. 
These macros have been deprecated and now is as good a time as any to remove them.

2022-09-20 18:22 UTC, allenjbaum commented
I'm unclear what has been deprecated; do you mean that #warning has been
deprecated in the toolchain?

On Tue, Sep 20, 2022 at 7:12 AM InspireSemi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> In test_macros.h
> The #warnings have been commented out. Either we uncomment these or just
> remove the this whole section from the file. Lines 768 - 818.
> These macros have been deprecated and now is as good a time as any to
> remove them.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/277#pullrequestreview-1113906240>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJUCZERQXXUX5DVEU3DV7HA4RANCNFSM56PYCGHQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-20 18:25 UTC, InspireSemi commented
The macros in this section of the header are marked as being deprecated.

Someone commented out the #warning messages that say this macro is deprecated since 3.0….

So either uncomment the #warning messages and leave the macros in place or remove the whole block of macros.

Marc Karasek
Principal Software Engineer
M: 678.770.3788

***@***.***
www.inspiresemi.com<http://www.cryptocoretech.com/>

THIS MESSAGE IS INTENDED ONLY FOR THE USE OF THE INDIVIDUAL OR ENTITY TO WHICH IT IS ADDRESSED AND MAY CONTAIN INFORMATION THAT IS PRIVILEGED, CONFIDENTIAL AND/OR EXEMPT FROM DISCLOSURE UNDER APPLICABLE LAW.  If the reader of this message is not the intended recipient or agent responsible for delivering the message to the intended recipient, then you are hereby notified that any dissemination or copying of this communication is strictly prohibited.  If you have received this electronic transmission in error, please delete it from your system without copying it and notify the sender by reply e-mail  so that our address record can be corrected.  Thank you.

From: Allen Baum ***@***.***>
Sent: Tuesday, September 20, 2022 2:23 PM
To: riscv-non-isa/riscv-arch-test ***@***.***>
Cc: Marc Karasek ***@***.***>; Comment ***@***.***>
Subject: Re: [riscv-non-isa/riscv-arch-test] Add changes in arch_test.h file, split macros into 2 files and enable multiple Privilege Modes in Trap Handler (PR #277)

I'm unclear what has been deprecated; do you mean that #warning has been
deprecated in the toolchain?

On Tue, Sep 20, 2022 at 7:12 AM InspireSemi ***@***.***<mailto:***@***.***>>
wrote:

> ***@***.****<mailto:***@***.****> requested changes on this pull request.
>
> In test_macros.h
> The #warnings have been commented out. Either we uncomment these or just
> remove the this whole section from the file. Lines 768 - 818.
> These macros have been deprecated and now is as good a time as any to
> remove them.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/277#pullrequestreview-1113906240>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJUCZERQXXUX5DVEU3DV7HA4RANCNFSM56PYCGHQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***<mailto:***@***.***>>
>


—
Reply to this email directly, view it on GitHub<https://github.com/riscv-non-isa/riscv-arch-test/pull/277#issuecomment-1252745250>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR3S6YZ5ZUGV7NHPMDXHBW3V7H6IVANCNFSM56PYCGHQ>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>

2022-09-20 18:36 UTC, allenjbaum commented
Ah, those macros. I thought you meant some other macros.
Yes, I think we can remove those.
I'll make sure these are removed when we merge the new trap handler, which
splits these off into test_macros.h

On Tue, Sep 20, 2022 at 11:25 AM InspireSemi ***@***.***>
wrote:

> The macros in this section of the header are marked as being deprecated.
>
> Someone commented out the #warning messages that say this macro is
> deprecated since 3.0….
>
> So either uncomment the #warning messages and leave the macros in place or
> remove the whole block of macros.
>
> Marc Karasek
> Principal Software Engineer
> M: 678.770.3788
>
> ***@***.***
> www.inspiresemi.com<http://www.cryptocoretech.com/>
>
> THIS MESSAGE IS INTENDED ONLY FOR THE USE OF THE INDIVIDUAL OR ENTITY TO
> WHICH IT IS ADDRESSED AND MAY CONTAIN INFORMATION THAT IS PRIVILEGED,
> CONFIDENTIAL AND/OR EXEMPT FROM DISCLOSURE UNDER APPLICABLE LAW. If the
> reader of this message is not the intended recipient or agent responsible
> for delivering the message to the intended recipient, then you are hereby
> notified that any dissemination or copying of this communication is
> strictly prohibited. If you have received this electronic transmission in
> error, please delete it from your system without copying it and notify the
> sender by reply e-mail so that our address record can be corrected. Thank
> you.
>
> From: Allen Baum ***@***.***>
> Sent: Tuesday, September 20, 2022 2:23 PM
> To: riscv-non-isa/riscv-arch-test ***@***.***>
> Cc: Marc Karasek ***@***.***>; Comment ***@***.***>
> Subject: Re: [riscv-non-isa/riscv-arch-test] Add changes in arch_test.h
> file, split macros into 2 files and enable multiple Privilege Modes in Trap
> Handler (PR #277)
>
> I'm unclear what has been deprecated; do you mean that #warning has been
> deprecated in the toolchain?
>
> On Tue, Sep 20, 2022 at 7:12 AM InspireSemi ***@***.***<mailto:***@***.***>>
>
> wrote:
>
> > ***@***.****<mailto:***@***.****> requested changes on this pull
> request.
> >
> > In test_macros.h
> > The #warnings have been commented out. Either we uncomment these or just
> > remove the this whole section from the file. Lines 768 - 818.
> > These macros have been deprecated and now is as good a time as any to
> > remove them.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/riscv-non-isa/riscv-arch-test/pull/277#pullrequestreview-1113906240>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AHPXVJUCZERQXXUX5DVEU3DV7HA4RANCNFSM56PYCGHQ>
>
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***<mailto:***@***.***>>
> >
>
>
> —
> Reply to this email directly, view it on GitHub<
> https://github.com/riscv-non-isa/riscv-arch-test/pull/277#issuecomment-1252745250>,
> or unsubscribe<
> https://github.com/notifications/unsubscribe-auth/AR3S6YZ5ZUGV7NHPMDXHBW3V7H6IVANCNFSM56PYCGHQ>.
>
> You are receiving this because you commented.Message ID:
> ***@***.******@***.***>>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/277#issuecomment-1252748194>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJQYL56O5UV4I3GVB5LV7H6STANCNFSM56PYCGHQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-10 04:25 UTC, UmerShahidengr commented
Hello,
As sent by @allenjbaum , this final commit is ready to be merged. Allen found and fixed a bunch of bugs related to: 
 -  code paths I haven't exercised that have vectored interrupt modes
 -  better indications of when the trap signature area is overrun
 - ensuring that the trap handler keeps the trampoline 64B aligned (need for CLIC spec)
 - fixing the handling of when xTVEC was not initialized and also could not be written
 - removing code that was compensating for Sail bugs
 - rewriting the save_GPR macro to it now compiles
 - some miscellaneous optimizations
 - comment fixes

2022-11-10 05:42 UTC, neelgala commented
A changelog entry is required. Please make this a "minor" update and in the Changelog be as detailed as possible in terms of the changes and feature additions that this PR introduces.

2022-11-10 06:26 UTC, UmerShahidengr commented
> A changelog entry is required. Please make this a "minor" update and in the Changelog be as detailed as possible in terms of the changes and feature additions that this PR introduces.

Done.

2022-11-10 07:25 UTC, pawks commented
There are some merge conflicts between the `arch_test.h` files on the main and the PR. Please pull the recent changes from main and resolve the conflicts correctly.

2022-11-10 13:04 UTC, UmerShahidengr commented
> There are some merge conflicts between the `arch_test.h` files on the main and the PR. Please pull the recent changes from main and resolve the conflicts correctly.

Done!

2022-11-10 17:01 UTC, UmerShahidengr commented
> The changes on the master are being overwritten. Especially the canary definitions [here](https://github.com/riscv-non-isa/riscv-arch-test/blob/b8e2315999bd8b7e849afb1126d6fa4d707b3c9b/riscv-test-suite/env/arch_test.h#L68-L74).

The CANARY error has been resolved. Now all (90) tests of RV32 are passing with the updated definition of CANARY.

2022-11-19 11:07 UTC, pawks requested changes

2022-11-19 11:07 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> -  #define LREGWU lwu
Definition of `LREGWU` is missing.

2022-11-19 11:07 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +#define LI(reg,val)			;\
This `LI` macro does not seem to work for all cases. For a few cases, no code is being generated. I have highlighted a few such cases below:

- `0x200000000000`
- `0x100000000`
- `0x8000000000`
- `0x80000000`
- `0x200000000`

2022-11-19 11:07 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +#define LI(reg,val)			;\
These are the inst 41,42 and 43 of the add test.

2022-11-19 11:07 UTC, pawks commented on riscv-test-suite/env/test_macros.h
> +	.set offset,_ARG1(__VA_ARGS__,0)		;\
Whenever arguments are being extracted from `__VA_ARGS__` it should be used with the `__VA_OPT__` macro, otherwise compilation errors will arise if no vardic arguments are passed to the macro. Refer to the latest macros on the main and update this file accordingly.

2022-11-19 11:07 UTC, pawks commented on riscv-test-suite/env/test_macros.h
> +#define TEST_STORE_F(swreg,testreg,index,rs1,rs2,rs2_val,imm_val,offset,inst,adj,flagreg) ;\
Multiple macros in this file are outdated. Please sync changes with master.

2022-11-19 11:07 UTC, pawks commented on riscv-test-suite/env/test_macros.h
> +#define TEST_STORE_F(swreg,testreg,index,rs1,rs2,rs2_val,imm_val,offset,inst,adj,flagreg) ;\
Multiple macros in this file are outdated. A lot of the macros have undergone multiple changes with multiple new ones defined. Please sync changes with main.

2022-11-19 11:07 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +#ifdef rvtest_sig_end				// if not defined, we can't test for overrun
`rvtest_sig_end` is a label and not a macro. `#ifdef` only tests whether a certain macro is defined. Hence this piece of code will never get compiled. The condition surrounding the code can be removed since all the tests on the main have been updated to define the required labels.

2022-11-19 11:07 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +  #ifndef rvtest_sig_begin						  ;\
`#ifndef` is being used to test for label definitions(which is wrong).

2022-11-19 11:07 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +rvtest_data_end:
The label should probably be moved to before the trap handler for increased accuracy?

2022-11-19 11:07 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +  #define SIGALIGN XLEN_WIDTH
`SIGALIGN` should be `REGWIDTH` instead of `XLEN_WIDTH` in this case.

2022-11-19 11:07 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +#define MASK ((1<<(XLEN-1))-1) + (1<<(XLEN-1))	// XLEN bits of 1s
One of the `MASK` or the `LI` macro(possibly both) is wrong. The code for loading values into the GPR file at the start of the test isn't being generated correctly.

2022-11-19 11:16 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +	SREG x\()__RNUM__,   \__RNUM__*REGWIDTH(x\()__TMP__)
This definition of RVTEST_SAVE_GPRS will not work as intended. The C style macros are evaluated before the assembly macros and assembly macros do not support stringification of arguments. Multiple compilation errors will be thrown if `rvtest_gpr_save` is defined during compilation.

2022-11-22 05:52 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> -  #define LREGWU lwu
This conditional macro definitions are only defining ops which are different for RV32 and RV64 so we dont need to define it.

2022-11-22 05:56 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> -  #define LREGWU lwu
It is necessary because of the unavailability of `lwu` in RV32 and the default behavior of `lw` in RV64 is signed. Hence `lwu` is required to perform appropriate loads incase of floating point tests.

2022-11-22 07:23 UTC, UmerShahidengr commented on riscv-test-suite/env/test_macros.h
> +	.set offset,_ARG1(__VA_ARGS__,0)		;\
Done

2022-11-22 07:25 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> -  #define LREGWU lwu
Right. Thanks for the correction.

2022-11-22 07:42 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +rvtest_data_end:
Increased accuracy of what? The trap handler be before the data area, in which case data_begin is > data_end, which messes things up.

2022-11-22 07:43 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> +rvtest_data_end:
Can you please elaborate this comment?

2022-11-22 07:56 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +#define MASK ((1<<(XLEN-1))-1) + (1<<(XLEN-1))	// XLEN bits of 1s
probably the bug in LI, now fixed.

2022-11-22 08:02 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +rvtest_data_end:
I was referring to the `mtrap_sigptr` label. This label is mainly used to detect memory access faults to the data region of the test. Any accesses to the `mtrap_sigptr` will never result in a fault, so the condition to infer that the fault is in the test data region should exclude these addresses. Including them does not introduce any problems but refining the positions definitely improves the quality.

2022-11-22 08:54 UTC, allenjbaum commented on riscv-test-suite/env/test_macros.h
> +	.set offset,_ARG1(__VA_ARGS__,0)		;\
fixed

2022-11-22 08:54 UTC, allenjbaum commented on riscv-test-suite/env/test_macros.h
> +#define TEST_STORE_F(swreg,testreg,index,rs1,rs2,rs2_val,imm_val,offset,inst,adj,flagreg) ;\
fixed

2022-11-22 08:54 UTC, allenjbaum commented on riscv-test-suite/env/test_macros.h
> +#define TEST_STORE_F(swreg,testreg,index,rs1,rs2,rs2_val,imm_val,offset,inst,adj,flagreg) ;\
fixed

2022-11-22 08:54 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +#ifdef rvtest_sig_end				// if not defined, we can't test for overrun
fixed

2022-11-22 08:55 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +  #define SIGALIGN XLEN_WIDTH
fixed

2022-11-22 09:04 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> -  #define LREGWU lwu
Done. Added changes in the latest commit

2022-11-22 09:05 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> +#define LI(reg,val)			;\
There was a bug in LI macro for numbers greater than 32bit. Well done on identifying it. Bug has been resolved now. LI macro is working correctly on those test numbers and on any 64bit immediate value

2022-11-22 09:06 UTC, UmerShahidengr commented on riscv-test-suite/env/test_macros.h
> +#define TEST_STORE_F(swreg,testreg,index,rs1,rs2,rs2_val,imm_val,offset,inst,adj,flagreg) ;\
Done. Added changes in the latest commit

2022-11-22 09:07 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> +  #ifndef rvtest_sig_begin						  ;\
Thanks for identifying the bug. Allen and I had an impression that ifdef and ifndef can work on labels too, but now we have cleaned up all instances of ifdef and ifndef in the whole code, and rectified all mistakes.

2022-11-22 09:07 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> +  #define SIGALIGN XLEN_WIDTH
Done. Added changes in the latest commit

2022-11-22 09:08 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> +	SREG x\()__RNUM__,   \__RNUM__*REGWIDTH(x\()__TMP__)
Definition of RVTEST_SAVE_GPRS has been updated.

2022-11-22 09:09 UTC, UmerShahidengr commented on riscv-test-suite/env/test_macros.h
> +#define TEST_STORE_F(swreg,testreg,index,rs1,rs2,rs2_val,imm_val,offset,inst,adj,flagreg) ;\
Done. All macro definitions are being re-synced with reference to the master

2022-11-22 09:31 UTC, UmerShahidengr commented
Added changes proposed in #294 into this PR.

2022-11-22 14:31 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +	SREG x\()__RNUM__,   \__RNUM__*REGWIDTH(x\()__TMP__)
That was an oversight; that macro was re-written but we missed including it.

2022-11-22 19:38 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +rvtest_data_end:
No, mtrap_sigptr is the address where the normal trap signature ends and the trap signature begins.
There is a variable in the trap handler that is initialized to this value, and gets incremented each time a trap signature is stored. It is also used as the relocation value to use when storing directly into the signature region and to calculate the trap signature size. It should not be moved anywhere

2022-11-23 09:14 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> -  #define LREGWU lwu
`LREGWU` should be defined as `lwu` in RV64 and `lw` in RV32. In the current state the tests will not compile for RV32IFD configuration.

2022-11-23 09:56 UTC, pawks requested changes

2022-11-23 09:56 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +  #ifdef RVTEST_GPR_SAVE	// gpr_save area is instantiated at end of signature
Macros are case sensitive. `RVTEST_GPR_SAVE` is used as `rvtest_gpr_save` in the tests([link](https://github.com/riscv-non-isa/riscv-arch-test/blob/c7ad0c84812e686c31e26df562a4784ed065b3f0/riscv-test-suite/rv32i_m/I/src/auipc-01.S#L399)).

2022-11-23 09:56 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +#define LI(reg,val)			;\
It is not fixed completely yet. Now no code is being generated for the following value:
- `0x80000000`

2022-11-23 09:56 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +#if SIGALIGN==8
Condition on `SIGALIGN` is being defined before the definition of the `SIGALIGN` macro itself. Macros are evaluated in the preprocessing phase and statically evaluated. The order of the definitions matters wherever the macros are used in the `#if` conditions. It is generally a good practice to always only use a macro after it has been defined.

2022-11-23 09:56 UTC, pawks commented on riscv-test-suite/env/arch_test.h
> +#if SIGALIGN==8
Similar problems exist for the `REGWIDTH` and other macros.

2022-11-23 14:51 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> -  #define LREGWU lwu
Done. Changes are made in latest commit

2022-11-23 14:52 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> +#define LI(reg,val)			;\
Now it has been fixed.

2022-11-23 14:53 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> +#if SIGALIGN==8
Done. The changes have been made in the latest commit

2022-11-23 17:14 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +  #ifdef RVTEST_GPR_SAVE	// gpr_save area is instantiated at end of signature
Oops - my bad. I got the RVTEST_SAVE_GPRS macro, and the separate rvtest_gpr_save macro that instantiates it mixed up.

2022-11-23 19:33 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> +  #ifdef RVTEST_GPR_SAVE	// gpr_save area is instantiated at end of signature
Done. RVTEST_GPR_SAVE has been replaced with rvtest_gpr_save and definition of RVTEST_SIG_END has been updated to simplify the tests

2022-11-24 06:35 UTC, pawks commented
Were you able to run the tests under `rv64i_m/C` directory? With the latest changes, all `C` extension tests fail to compile. This is probably because of a `.option norvc` in the template macros which is not clubbed with a `.option push ... .option pop` sequence.  An instance of the error is shown below:
```
Error: unrecognized opcode `c.addi16sp x2,0x100'
```

2022-12-22 19:06 UTC, pawks commented on riscv-test-suite/env/test_macros.h
> +  SREG _F,offset+SIGALIGN(_BR)				;\
Incorrect definition of the SIGUPD_F macros. The offset is already being incremented as a part of the `CHK_OFFSET` macro by setting `PRE_INC` to `1` in this instance and hence it is not necessary to increment it outside.

2022-12-22 19:09 UTC, pawks commented on riscv-test-suite/env/test_macros.h
> +  SREG _F,offset+REGWIDTH(_BR)				;\
Similar to the bug in SIGUPD_F macro.

2022-12-23 00:13 UTC, allenjbaum commented on riscv-test-suite/env/test_macros.h
> +  SREG _F,offset+SIGALIGN(_BR)				;\
Ah, I see; I was looking in the wrong place .
The second SREG shouldn't have the offset+SIGALIGN() term, it should just be offset(). That is true for all the SIGUPD_x macros, not just these two.

2022-12-23 05:17 UTC, pawks commented on riscv-test-suite/env/test_macros.h
> +  SREG _F,offset+SIGALIGN(_BR)				;\
The latest macros on the main have been fixed([link](https://github.com/riscv-non-isa/riscv-arch-test/blob/e302d3bab41a46ec388691b1d961aa09fe2a4bc4/riscv-test-suite/env/arch_test.h#L661)). By introducing the `offset+SIGALIGN` the tests do not compile because an overflow occurs after a few instances of the macro in the test, specifically at line 106. In its current form, it also results in the flag values of preceding test instance getting overwritten by the result of the next instance.

2022-12-23 08:14 UTC, allenjbaum commented
An overflow?Not sure what that means.  The code above (or below, I guess)
is not the correct fix.
All Instances of SREG or FSREG, offset+SIGALIGN(_BR)
should be changed to     FSREG, offset(_BR)
because the CHK_OFFSET(_BR,SIGALIGN,1) pre-increment the offset.

On Thu, Dec 22, 2022 at 9:17 PM S Pawan Kumar ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In riscv-test-suite/env/test_macros.h
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/277#discussion_r1056044807>
> :
>
> > +/* It stores both an Xreg and an Freg, first adjusting base & offset to	 */
> +/* to keep offset < 2048. SIGALIGN is set to the max(FREGWIDTH, REGWIDTH)*/
> +/* _BR - Base Reg, _R - FReg, _F - Fstatus Xreg				 */
> +#define RVTEST_SIGUPD_F(_BR,_R,_F,...)			;\
> +  .if NARG(__VA_ARGS__) == 1				;\
> +     .set offset,_ARG1(__VA_OPT__(__VA_ARGS__,0))	;\
> +  .endif						;\
> +  .if (offset&(SIGALIGN-1))!=0				;\
> +/* Throw warnings then modify offset to target */	;\
> +     .warning "Incorrect signature Offset Alignment."	;\
> +     .set offset, offset&(SIGALIGN-1)+SIGALIGN		;\
> +  .endif						;\
> +  CHK_OFFSET(_BR, SIGALIGN, 0)				;\
> +  FSREG _R,offset(_BR)					;\
> +  CHK_OFFSET(_BR, SIGALIGN, 1)				;\
> +  SREG _F,offset+SIGALIGN(_BR)				;\
>
> The latest macros on the main have been fixed(link
> <https://github.com/riscv-non-isa/riscv-arch-test/blob/e302d3bab41a46ec388691b1d961aa09fe2a4bc4/riscv-test-suite/env/arch_test.h#L661>).
> By introducing the offset+SIGALIGN the tests do not compile because an
> overflow occurs after a few instances of the macro in the test,
> specifically at line 106. In its current form, it also results in the flag
> values of preceding test instance getting overwritten by the result of the
> next instance.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/277#discussion_r1056044807>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJRNWILXUQCILOPA3FDWOUYV5ANCNFSM56PYCGHQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-23 08:16 UTC, allenjbaum commented
More correctly, in case this is misinterpreted:
All Instances of            SREG/FSREG, offset+SIGALIGN(_BR)
should be changed to  SREG/FSREG, offset(_BR)

On Fri, Dec 23, 2022 at 12:14 AM Allen Baum ***@***.***>
wrote:

> An overflow?Not sure what that means.  The code above (or below, I guess)
> is not the correct fix.
> All Instances of SREG or FSREG, offset+SIGALIGN(_BR)
> should be changed to     FSREG, offset(_BR)
> because the CHK_OFFSET(_BR,SIGALIGN,1) pre-increment the offset.
>
> On Thu, Dec 22, 2022 at 9:17 PM S Pawan Kumar ***@***.***>
> wrote:
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In riscv-test-suite/env/test_macros.h
>> <https://github.com/riscv-non-isa/riscv-arch-test/pull/277#discussion_r1056044807>
>> :
>>
>> > +/* It stores both an Xreg and an Freg, first adjusting base & offset to	 */
>> +/* to keep offset < 2048. SIGALIGN is set to the max(FREGWIDTH, REGWIDTH)*/
>> +/* _BR - Base Reg, _R - FReg, _F - Fstatus Xreg				 */
>> +#define RVTEST_SIGUPD_F(_BR,_R,_F,...)			;\
>> +  .if NARG(__VA_ARGS__) == 1				;\
>> +     .set offset,_ARG1(__VA_OPT__(__VA_ARGS__,0))	;\
>> +  .endif						;\
>> +  .if (offset&(SIGALIGN-1))!=0				;\
>> +/* Throw warnings then modify offset to target */	;\
>> +     .warning "Incorrect signature Offset Alignment."	;\
>> +     .set offset, offset&(SIGALIGN-1)+SIGALIGN		;\
>> +  .endif						;\
>> +  CHK_OFFSET(_BR, SIGALIGN, 0)				;\
>> +  FSREG _R,offset(_BR)					;\
>> +  CHK_OFFSET(_BR, SIGALIGN, 1)				;\
>> +  SREG _F,offset+SIGALIGN(_BR)				;\
>>
>> The latest macros on the main have been fixed(link
>> <https://github.com/riscv-non-isa/riscv-arch-test/blob/e302d3bab41a46ec388691b1d961aa09fe2a4bc4/riscv-test-suite/env/arch_test.h#L661>).
>> By introducing the offset+SIGALIGN the tests do not compile because an
>> overflow occurs after a few instances of the macro in the test,
>> specifically at line 106. In its current form, it also results in the flag
>> values of preceding test instance getting overwritten by the result of the
>> next instance.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/riscv-non-isa/riscv-arch-test/pull/277#discussion_r1056044807>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AHPXVJRNWILXUQCILOPA3FDWOUYV5ANCNFSM56PYCGHQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-12-23 17:23 UTC, allenjbaum commented on riscv-test-suite/env/test_macros.h
> +  SREG _F,offset+SIGALIGN(_BR)				;\
I don't understand. The "offset+SIGALIGN" terms should be removed from all SIGUPD macros, and be replaced with just "offset". That's the bug you found above. I can see where that would cause the code to hit the overrun code.

2022-12-27 08:58 UTC, UmerShahidengr commented on riscv-test-suite/env/test_macros.h
> +  SREG _F,offset+SIGALIGN(_BR)				;\
The latest commit has eliminated this mistake

2022-12-27 08:58 UTC, UmerShahidengr commented on riscv-test-suite/env/test_macros.h
> +  SREG _F,offset+REGWIDTH(_BR)				;\
Resolved

2023-01-18 05:41 UTC, allenjbaum requested changes
There are numerous problems with this fix. There are some fixes, also, but this isn't ready for prime time.

2023-01-25 10:41 UTC, pawks approved these changes
All changes look good to me. The current tests pass. LGTM

2023-01-25 20:03 UTC, allenjbaum approved these changes

2023-01-25 20:03 UTC, merged