Add support for the Zicond ISA extension
riscv-non-isa/riscv-arch-test pull request #321
Opened 2023-03-21 19:59 UTC by cmuellner

This patch intoduces a coverage model and the generated test cases using riscv_ctg.

The tests have been generated using the following command:
  riscv_ctg.py \
    --cgf coverage/dataset.cgf \
    --cgf coverage/zicond.cgf \
    -bi rv32i \
    -d tests/
  riscv_ctg.py \
    --cgf coverage/dataset.cgf \
    --cgf coverage/zicond.cgf \
    -bi rv64i \
    -d tests64/

The resulting tests have been copied to the target directory:
  cp tests/*S riscv-test-suite/rv32i_m/Zicond/src/
  cp tests64/*S riscv-test-suite/rv64i_m/Zicond/src/

This PR depends on Zicond support in the riscv-ctg repo:
  https://github.com/riscv-software-src/riscv-ctg/pull/59

<FOR DOC UPDATES FILL ONLY DESCRIPTION AND RELATED ISSUES SECTION AND REMOVE THE OTHERS>

## Description

> Provide a detailed description of the changes performed by the PR.

### Related Issues

> Please list all the issues related to this PR. Use NA if no issues exist

### Ratified/Unratified Extensions

- [ ] Ratified
- [ ] Unratified

### List Extensions

> List the extensions that your PR affects. In case of unratified extensions, please provide a link to the spec draft that was referred to make this PR.

### Reference Model Used

- [ ] SAIL
- [ ] Spike
- [ ] Other - < SPECIFY HERE >

### Mandatory Checklist:

  - [ ] All tests are compliant with the test-format spec present in this repo ?
  - [ ] Ran the new tests on RISCOF with SAIL/Spike as reference model successfully ?
  - [ ] Ran the new tests on RISCOF in [coverage mode](https://riscof.readthedocs.io/en/stable/commands.html#coverage)
  - [ ] Link to Google-Drive folder containing the new coverage reports ([See this](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/CONTRIBUTION.md#uploading-test-stats) for more info): < SPECIFY HERE >
  - [ ] Link to PR in RISCV-ISAC from which the reports were generated : < SPECIFY HERE > 
  - [ ] Changelog entry created with a minor patch

### Optional Checklist:

  - [ ] RISCV-V CTG PR link if tests were generated using it : < SPECIFY HERE >
  - [ ] Were the tests hand-written/modified ?
  - [ ] Have you run these on any hard DUT model ? Please specify name and provide link if possible in the description
  - [ ] If you have modified arch\_test.h Please provide a detailed description of the changes in the Description section above.

2023-04-06 21:03 UTC, charmitro commented
Link for test results using RISCOF can be [found here](https://drive.google.com/drive/folders/1DCz8RRph2q35mny379FlqJDdx4K8JfzG?usp=share_link).

2023-08-18 09:56 UTC, UmerShahidengr commented
Zicond extension has no support in either Sail or gcc compiler. Can you give any pointer on which compiler toolchain have you used to build these tests and how have you run these tests on riscof?

2023-08-21 07:47 UTC, cmuellner commented
> Zicond extension has no support in either Sail or gcc compiler. Can you give any pointer on which compiler toolchain have you used to build these tests and how have you run these tests on riscof?

Zicond support for Binutils is upstream for quite some time: https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=b625eff8a2346fe1107aa4ab7bbf4302f2c2136e

GCC support is not needed for this repository.

The changes for CTG are linked in the description of this PR (https://github.com/riscv-software-src/riscv-ctg/pull/59).

Zicond support for Sail has been merged a few months ago: https://github.com/riscv/sail-riscv/pull/206

The exact commands to generate the tests can be found in the description of the PR.

2023-08-21 08:34 UTC, charmitro commented
> Zicond extension has no support in either Sail or gcc compiler. Can you give any pointer on which compiler toolchain have you used to build these tests and how have you run these tests on riscof?

To execute the tests, ensure you have the appropriate versions of Binutils, Spike, and SAIL installed. Once verified, you can initiate the tests using:
```bash
$ riscof testlist --config config.ini --suite riscv-arch-test/riscv-test-suite/rv64i_m/Zicond/ --env=riscv-arch-test/riscv-test-suite/env
[ ... ]
$ riscof run --config config.ini --suite riscv-arch-test/riscv-test-suite/rv64i_m/Zicond/ --env=riscv-arch-test/riscv-test-suite/env --no-browser
    INFO | TEST NAME                                          : COMMIT ID                                : STATUS
    INFO | /home/cmitrodimas/repositories/ACT-related/ACTs/riscv-arch-test/riscv-test-suite/rv64i_m/Zicond/src/czero.eqz-01.S : -                                        : Passed
    INFO | /home/cmitrodimas/repositories/ACT-related/ACTs/riscv-arch-test/riscv-test-suite/rv64i_m/Zicond/src/czero.nez-01.S : -                                        : Passed
    INFO | Test report generated at /home/cmitrodimas/repositories/ACT-related/ACTs/riscof_work/report.html.
```

2023-08-22 16:17 UTC, UmerShahidengr commented
Thanks. I will make it work at my end.

2023-08-30 09:46 UTC, UmerShahidengr commented
@charmitro I have updated binutils but upon compilation, it is giving unrecognized opcode error on czero.nez.
Can you share the binaries and/or exact versions of your riscv toolchain, binutils, and riscof please?

2023-08-30 10:46 UTC, cmuellner commented
> @charmitro I have updated binutils but upon compilation, it is giving unrecognized opcode error on czero.nez. Can you share the binaries and/or exact versions of your riscv toolchain, binutils, and riscof please?

What is the exact error message?

2023-09-01 08:11 UTC, UmerShahidengr commented
@cmuellner  The exact error message is ``Error: unrecognized opcode `czero.eqz x31,x30,x29'```
It is because I have not enabled Zicond and I am having trouble enabling it as I am not an expert in using binary utlities. It will be best if you send me the binary files of these tests.

2023-09-05 08:47 UTC, UmerShahidengr commented
@charmitro , @cmuellner kind reminder. Can I get the binaries of Zicond tests?

2023-11-17 05:24 UTC, UmerShahidengr commented on CHANGELOG.md
> +## [3.6.3] - 2023-03-21
You need to change this Changelog entry as there are a lot of PRs merged since this update, and this version number is taken.

2023-11-17 05:26 UTC, UmerShahidengr requested changes
Update the Changelog file, rest of the files are ready to go.

2023-11-17 09:03 UTC, cmuellner commented
Updating the Changelog of all PRs after each new commit on master does not scale.
There is also no "update the Changelog file". Instead a rebase is required.
And rebasing after 8 (!) months usually requires re-testing.
How can I justify these efforts, when at the end of the day the PR might just be ignored for at least another 8 months?

Also, it seems you solved the issues with your toolchain. It would be great to share your solution, so that others which face the same issue can learn from your solution.

2023-11-17 09:14 UTC, UmerShahidengr commented
> Updating the Changelog of all PRs after each new commit on master does not scale.
> There is also no "update the Changelog file". Instead a rebase is required.
> And rebasing after 8 (!) months usually requires re-testing.
> How can I justify these efforts, when at the end of the day the PR might just be ignored for at least another 8 months?

You are absolutely right. Some moderator/writer will be assigned soon by sig-arch-tests team who will be managing this Changelog issue in future to make it scalable. @allenjbaum and co are working on our governance policies. For this time only, in order to remove the backlog, you are requested to update the file manually as nobody else the write access to this PR. Once you resolve the conflict, this PR will be merged right away.

2023-11-17 09:15 UTC, UmerShahidengr commented
> Also, it seems you solved the issues with your toolchain. It would be great to share your solution, so that others which face the same issue can learn from your solution.

Yes I resolved the issue, I found the gcc patch online which compiled the tests and I executed it successfully

2023-11-17 09:29 UTC, cmuellner commented
PR has been rebase and Changelog has been updated (new version and today's date).

2023-11-17 09:33 UTC, UmerShahidengr approved these changes
Good to go now.

2023-11-30 17:05 UTC, cmuellner commented
> Once you resolve the conflict, this PR will be merged right away.

@UmerShahidengr: We already ran into a new conflict, since other PRs were merged since you requested my update. And the request-for-update and the update were made two weeks ago.

2023-12-01 07:06 UTC, allenjbaum approved these changes
resolved merge conflicts in changelog & updated the date

2023-12-01 07:06 UTC, merged

2023-12-01 08:43 UTC, cmuellner commented
Thanks, @allenjbaum, @UmerShahidengr, and @charmitro!

Perfect timing, as Zicond's ratification has just been announced.