Added Zfinx and Zfh tests
riscv-non-isa/riscv-arch-test pull request #367
Opened 2023-07-03 06:09 UTC by anuani21

<FOR DOC UPDATES FILL ONLY DESCRIPTION AND RELATED ISSUES SECTION AND REMOVE THE OTHERS>

## Description

-   Zfh and Zfinx Test are added
- Added half width and half word into the NAN function to accommodate Zfh, as the base for Zfh is F which is also falls under the value as word
- Introduced two new flags (ZFINX and ZDINX) to aid the compilation of floating ops into integer regs

### Related Issues
 NA

### Ratified/Unratified Extensions

[✓] Ratified

### List Extensions

- Zfinx
- Zfh

### Reference Model Used

[✓] SAIL

### Mandatory Checklist:

Ran reports are placed here

https://gitlab.com/ptprasanna/actreports.git

2023-07-03 06:39 UTC, pawks commented
As already discussed, this PR can be merged only after the corresponding PR for ISAC has been merged.

2023-12-28 11:18 UTC, davidharrishmc commented
I would use these tests on CORE-V Wally when they are available.

PR72 for ISAC has been merged.
https://github.com/riscv-software-src/riscv-isac/pull/72

PR67 from CTG has been waiting for review since July 2.
https://github.com/riscv-software-src/riscv-ctg/pull/67

2024-01-03 07:06 UTC, anuani21 commented
@neelgala , -Please have your review and let us know if more information would help.

2024-01-15 17:31 UTC, davidharrishmc commented
I see there are no fma tests in this directory.  Is there a reason these are omitted?

2024-01-16 04:18 UTC, anuani21 commented
Hi,

As per the Zfinx and Zfh specification, there is no fma tests available I
think

On Mon, Jan 15, 2024 at 11:01 PM David Harris ***@***.***>
wrote:

> I see there are no fma tests in this directory. Is there a reason these
> are omitted?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1892560832>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3G6FF7QWJ44KEAEENHUWZLYOVRXRAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJSGU3DAOBTGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-16 04:22 UTC, davidharrishmc commented
Got it. Thanks!

On Mon, Jan 15, 2024 at 8:18 PM anuani21 ***@***.***> wrote:

> Hi,
>
> As per the Zfinx and Zfh specification, there is no fma tests available I
> think
>
> On Mon, Jan 15, 2024 at 11:01 PM David Harris ***@***.***>
> wrote:
>
> > I see there are no fma tests in this directory. Is there a reason these
> > are omitted?
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1892560832>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/A3G6FF7QWJ44KEAEENHUWZLYOVRXRAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJSGU3DAOBTGI>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1893046699>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR4AA37ZAEBKH7BPOFP4F4LYOX5R3AVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJTGA2DMNRZHE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-01-24 15:35 UTC, davidharrishmc commented
On further review of the ratified Zfh spec, there are fmadd.h and related instructions.  See the bottom figure of Section 15.2.


https://wiki.riscv.org/display/HOME/Recently+Ratified+Extensions
https://drive.google.com/file/d/1z3tQQLm5ALsAD77PM0l0CHnapxWCeVzP/view

2024-01-24 17:44 UTC, allenjbaum commented
I'm not sure how to interpret that.
 "The Zfinx extension adds all of the instructions that the F extension
adds, except for the transfer instructions FLW, FSW, FMV.W.X, FMV.X.W,
C.FLW[SP], and C.FSW[SP]."

So, there should be FMA tests.

On Mon, Jan 15, 2024 at 8:22 PM David Harris ***@***.***>
wrote:

> Got it. Thanks!
>
> On Mon, Jan 15, 2024 at 8:18 PM anuani21 ***@***.***> wrote:
>
> > Hi,
> >
> > As per the Zfinx and Zfh specification, there is no fma tests available
> I
> > think
> >
> > On Mon, Jan 15, 2024 at 11:01 PM David Harris ***@***.***>
> > wrote:
> >
> > > I see there are no fma tests in this directory. Is there a reason
> these
> > > are omitted?
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1892560832>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/A3G6FF7QWJ44KEAEENHUWZLYOVRXRAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJSGU3DAOBTGI>
>
> >
> > > .
> > > You are receiving this because you authored the thread.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1893046699>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AR4AA37ZAEBKH7BPOFP4F4LYOX5R3AVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJTGA2DMNRZHE>
>
> > .
> > You are receiving this because you commented.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1893049151>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJXXCEAZ6Q62RFN4XULYOX6AZAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJTGA2DSMJVGE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-01-25 01:36 UTC, anuani21 commented
Hi,

I thought fma and fmadd instructions are different. Fmadd and fmsub
instructions are available in zfh and zfinx. I will upload the coverage
report for fmadd and fmsub instructions shortly.

On Wed, 24 Jan, 2024, 11:14 pm Allen Baum, ***@***.***> wrote:

> I'm not sure how to interpret that.
> "The Zfinx extension adds all of the instructions that the F extension
> adds, except for the transfer instructions FLW, FSW, FMV.W.X, FMV.X.W,
> C.FLW[SP], and C.FSW[SP]."
>
> So, there should be FMA tests.
>
> On Mon, Jan 15, 2024 at 8:22 PM David Harris ***@***.***>
> wrote:
>
> > Got it. Thanks!
> >
> > On Mon, Jan 15, 2024 at 8:18 PM anuani21 ***@***.***> wrote:
> >
> > > Hi,
> > >
> > > As per the Zfinx and Zfh specification, there is no fma tests
> available
> > I
> > > think
> > >
> > > On Mon, Jan 15, 2024 at 11:01 PM David Harris ***@***.***>
> > > wrote:
> > >
> > > > I see there are no fma tests in this directory. Is there a reason
> > these
> > > > are omitted?
> > > >
> > > > —
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > >
> >
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1892560832>,
>
> >
> > >
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/A3G6FF7QWJ44KEAEENHUWZLYOVRXRAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJSGU3DAOBTGI>
>
> >
> > >
> > > > .
> > > > You are receiving this because you authored the thread.Message ID:
> > > > ***@***.***>
> > > >
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1893046699>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/AR4AA37ZAEBKH7BPOFP4F4LYOX5R3AVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJTGA2DMNRZHE>
>
> >
> > > .
> > > You are receiving this because you commented.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1893049151>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AHPXVJXXCEAZ6Q62RFN4XULYOX6AZAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJTGA2DSMJVGE>
>
> > .
> > You are receiving this because you are subscribed to this thread.Message
> > ID: ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1908627624>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3G6FFZOUYDQ4OCBPG2HT53YQFCAJAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBYGYZDONRSGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-25 05:04 UTC, davidharrishmc commented
Remember that there are fnmadd and fnmsub as well in the FMA class of instructions.

> On Jan 24, 2024, at 5:36 PM, anuani21 ***@***.***> wrote:
> 
> 
> Hi, 
> 
> I thought fma and fmadd instructions are different. Fmadd and fmsub 
> instructions are available in zfh and zfinx. I will upload the coverage 
> report for fmadd and fmsub instructions shortly. 
> 
> On Wed, 24 Jan, 2024, 11:14 pm Allen Baum, ***@***.***> wrote: 
> 
> > I'm not sure how to interpret that. 
> > "The Zfinx extension adds all of the instructions that the F extension 
> > adds, except for the transfer instructions FLW, FSW, FMV.W.X, FMV.X.W, 
> > C.FLW[SP], and C.FSW[SP]." 
> > 
> > So, there should be FMA tests. 
> > 
> > On Mon, Jan 15, 2024 at 8:22 PM David Harris ***@***.***> 
> > wrote: 
> > 
> > > Got it. Thanks! 
> > > 
> > > On Mon, Jan 15, 2024 at 8:18 PM anuani21 ***@***.***> wrote: 
> > > 
> > > > Hi, 
> > > > 
> > > > As per the Zfinx and Zfh specification, there is no fma tests 
> > available 
> > > I 
> > > > think 
> > > > 
> > > > On Mon, Jan 15, 2024 at 11:01 PM David Harris ***@***.***> 
> > > > wrote: 
> > > > 
> > > > > I see there are no fma tests in this directory. Is there a reason 
> > > these 
> > > > > are omitted? 
> > > > > 
> > > > > — 
> > > > > Reply to this email directly, view it on GitHub 
> > > > > < 
> > > > 
> > > 
> > https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1892560832>, 
> > 
> > > 
> > > > 
> > > > > or unsubscribe 
> > > > > < 
> > > > 
> > > 
> > https://github.com/notifications/unsubscribe-auth/A3G6FF7QWJ44KEAEENHUWZLYOVRXRAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJSGU3DAOBTGI> 
> > 
> > > 
> > > > 
> > > > > . 
> > > > > You are receiving this because you authored the thread.Message ID: 
> > > > > ***@***.***> 
> > > > > 
> > > > 
> > > > — 
> > > > Reply to this email directly, view it on GitHub 
> > > > < 
> > > 
> > https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1893046699>, 
> > 
> > > 
> > > > or unsubscribe 
> > > > < 
> > > 
> > https://github.com/notifications/unsubscribe-auth/AR4AA37ZAEBKH7BPOFP4F4LYOX5R3AVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJTGA2DMNRZHE> 
> > 
> > > 
> > > > . 
> > > > You are receiving this because you commented.Message ID: 
> > > > ***@***.***> 
> > > > 
> > > 
> > > — 
> > > Reply to this email directly, view it on GitHub 
> > > < 
> > https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1893049151>, 
> > 
> > > or unsubscribe 
> > > < 
> > https://github.com/notifications/unsubscribe-auth/AHPXVJXXCEAZ6Q62RFN4XULYOX6AZAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJTGA2DSMJVGE> 
> > 
> > > . 
> > > You are receiving this because you are subscribed to this thread.Message 
> > > ID: ***@***.***> 
> > > 
> > 
> > — 
> > Reply to this email directly, view it on GitHub 
> > <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1908627624>, 
> > or unsubscribe 
> > <https://github.com/notifications/unsubscribe-auth/A3G6FFZOUYDQ4OCBPG2HT53YQFCAJAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBYGYZDONRSGQ> 
> > . 
> > You are receiving this because you authored the thread.Message ID: 
> > ***@***.***> 
> > 
> —
> Reply to this email directly, view it on GitHub <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1909201935>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AR4AA32MAHIUM2H2L7SQWXTYQGZJPAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBZGIYDCOJTGU>.
> You are receiving this because you commented.
>

2024-01-25 05:12 UTC, anuani21 commented
Ya sure I will upload fmadd,fmsub,fnmadd and fnmsub instructions.

On Thu, Jan 25, 2024 at 10:34 AM David Harris ***@***.***>
wrote:

> Remember that there are fnmadd and fnmsub as well in the FMA class of
> instructions.
>
> > On Jan 24, 2024, at 5:36 PM, anuani21 ***@***.***> wrote:
> >
> >
> > Hi,
> >
> > I thought fma and fmadd instructions are different. Fmadd and fmsub
> > instructions are available in zfh and zfinx. I will upload the coverage
> > report for fmadd and fmsub instructions shortly.
> >
> > On Wed, 24 Jan, 2024, 11:14 pm Allen Baum, ***@***.***> wrote:
> >
> > > I'm not sure how to interpret that.
> > > "The Zfinx extension adds all of the instructions that the F extension
> > > adds, except for the transfer instructions FLW, FSW, FMV.W.X, FMV.X.W,
> > > C.FLW[SP], and C.FSW[SP]."
> > >
> > > So, there should be FMA tests.
> > >
> > > On Mon, Jan 15, 2024 at 8:22 PM David Harris ***@***.***>
> > > wrote:
> > >
> > > > Got it. Thanks!
> > > >
> > > > On Mon, Jan 15, 2024 at 8:18 PM anuani21 ***@***.***> wrote:
> > > >
> > > > > Hi,
> > > > >
> > > > > As per the Zfinx and Zfh specification, there is no fma tests
> > > available
> > > > I
> > > > > think
> > > > >
> > > > > On Mon, Jan 15, 2024 at 11:01 PM David Harris ***@***.***>
> > > > > wrote:
> > > > >
> > > > > > I see there are no fma tests in this directory. Is there a
> reason
> > > > these
> > > > > > are omitted?
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly, view it on GitHub
> > > > > > <
> > > > >
> > > >
> > >
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1892560832>,
>
> > >
> > > >
> > > > >
> > > > > > or unsubscribe
> > > > > > <
> > > > >
> > > >
> > >
> https://github.com/notifications/unsubscribe-auth/A3G6FF7QWJ44KEAEENHUWZLYOVRXRAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJSGU3DAOBTGI>
>
> > >
> > > >
> > > > >
> > > > > > .
> > > > > > You are receiving this because you authored the thread.Message
> ID:
> > > > > > ***@***.***>
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly, view it on GitHub
> > > > > <
> > > >
> > >
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1893046699>,
>
> > >
> > > >
> > > > > or unsubscribe
> > > > > <
> > > >
> > >
> https://github.com/notifications/unsubscribe-auth/AR4AA37ZAEBKH7BPOFP4F4LYOX5R3AVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJTGA2DMNRZHE>
>
> > >
> > > >
> > > > > .
> > > > > You are receiving this because you commented.Message ID:
> > > > > ***@***.***>
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > >
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1893049151>,
>
> > >
> > > > or unsubscribe
> > > > <
> > >
> https://github.com/notifications/unsubscribe-auth/AHPXVJXXCEAZ6Q62RFN4XULYOX6AZAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJTGA2DSMJVGE>
>
> > >
> > > > .
> > > > You are receiving this because you are subscribed to this
> thread.Message
> > > > ID: ***@***.***>
> > > >
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1908627624>,
>
> > > or unsubscribe
> > > <
> https://github.com/notifications/unsubscribe-auth/A3G6FFZOUYDQ4OCBPG2HT53YQFCAJAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBYGYZDONRSGQ>
>
> > > .
> > > You are receiving this because you authored the thread.Message ID:
> > > ***@***.***>
> > >
> > —
> > Reply to this email directly, view it on GitHub <
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1909201935>,
> or unsubscribe <
> https://github.com/notifications/unsubscribe-auth/AR4AA32MAHIUM2H2L7SQWXTYQGZJPAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBZGIYDCOJTGU>.
>
> > You are receiving this because you commented.
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1909361508>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3G6FF5NFY2OK4I5HT2RS7DYQHRXPAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBZGM3DCNJQHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-25 07:05 UTC, allenjbaum commented
Ah, I thought you were using fma as the generic for fm[n][add/sub]

On Wed, Jan 24, 2024 at 9:12 PM anuani21 ***@***.***> wrote:

> Ya sure I will upload fmadd,fmsub,fnmadd and fnmsub instructions.
>
> On Thu, Jan 25, 2024 at 10:34 AM David Harris ***@***.***>
> wrote:
>
> > Remember that there are fnmadd and fnmsub as well in the FMA class of
> > instructions.
> >
> > > On Jan 24, 2024, at 5:36 PM, anuani21 ***@***.***> wrote:
> > >
> > >
> > > Hi,
> > >
> > > I thought fma and fmadd instructions are different. Fmadd and fmsub
> > > instructions are available in zfh and zfinx. I will upload the
> coverage
> > > report for fmadd and fmsub instructions shortly.
> > >
> > > On Wed, 24 Jan, 2024, 11:14 pm Allen Baum, ***@***.***> wrote:
> > >
> > > > I'm not sure how to interpret that.
> > > > "The Zfinx extension adds all of the instructions that the F
> extension
> > > > adds, except for the transfer instructions FLW, FSW, FMV.W.X,
> FMV.X.W,
> > > > C.FLW[SP], and C.FSW[SP]."
> > > >
> > > > So, there should be FMA tests.
> > > >
> > > > On Mon, Jan 15, 2024 at 8:22 PM David Harris ***@***.***>
> > > > wrote:
> > > >
> > > > > Got it. Thanks!
> > > > >
> > > > > On Mon, Jan 15, 2024 at 8:18 PM anuani21 ***@***.***> wrote:
> > > > >
> > > > > > Hi,
> > > > > >
> > > > > > As per the Zfinx and Zfh specification, there is no fma tests
> > > > available
> > > > > I
> > > > > > think
> > > > > >
> > > > > > On Mon, Jan 15, 2024 at 11:01 PM David Harris ***@***.***>
> > > > > > wrote:
> > > > > >
> > > > > > > I see there are no fma tests in this directory. Is there a
> > reason
> > > > > these
> > > > > > > are omitted?
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > <
> > > > > >
> > > > >
> > > >
> >
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1892560832>,
>
> >
> > > >
> > > > >
> > > > > >
> > > > > > > or unsubscribe
> > > > > > > <
> > > > > >
> > > > >
> > > >
> >
> https://github.com/notifications/unsubscribe-auth/A3G6FF7QWJ44KEAEENHUWZLYOVRXRAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJSGU3DAOBTGI>
>
> >
> > > >
> > > > >
> > > > > >
> > > > > > > .
> > > > > > > You are receiving this because you authored the thread.Message
> > ID:
> > > > > > > ***@***.***>
> > > > > > >
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly, view it on GitHub
> > > > > > <
> > > > >
> > > >
> >
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1893046699>,
>
> >
> > > >
> > > > >
> > > > > > or unsubscribe
> > > > > > <
> > > > >
> > > >
> >
> https://github.com/notifications/unsubscribe-auth/AR4AA37ZAEBKH7BPOFP4F4LYOX5R3AVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJTGA2DMNRZHE>
>
> >
> > > >
> > > > >
> > > > > > .
> > > > > > You are receiving this because you commented.Message ID:
> > > > > > ***@***.***>
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly, view it on GitHub
> > > > > <
> > > >
> >
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1893049151>,
>
> >
> > > >
> > > > > or unsubscribe
> > > > > <
> > > >
> >
> https://github.com/notifications/unsubscribe-auth/AHPXVJXXCEAZ6Q62RFN4XULYOX6AZAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJTGA2DSMJVGE>
>
> >
> > > >
> > > > > .
> > > > > You are receiving this because you are subscribed to this
> > thread.Message
> > > > > ID: ***@***.***>
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly, view it on GitHub
> > > > <
> >
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1908627624>,
>
> >
> > > > or unsubscribe
> > > > <
> >
> https://github.com/notifications/unsubscribe-auth/A3G6FFZOUYDQ4OCBPG2HT53YQFCAJAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBYGYZDONRSGQ>
>
> >
> > > > .
> > > > You are receiving this because you authored the thread.Message ID:
> > > > ***@***.***>
> > > >
> > > —
> > > Reply to this email directly, view it on GitHub <
> >
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1909201935>,
>
> > or unsubscribe <
> >
> https://github.com/notifications/unsubscribe-auth/AR4AA32MAHIUM2H2L7SQWXTYQGZJPAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBZGIYDCOJTGU>.
>
> >
> > > You are receiving this because you commented.
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1909361508>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/A3G6FF5NFY2OK4I5HT2RS7DYQHRXPAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBZGM3DCNJQHA>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1909367761>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJQTYXASI2CFS7JCQDDYQHSTVAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBZGM3DONZWGE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-01-30 17:27 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +#elif ZDINX==1
This looks wrong; ZFinx only needs 4B registers, NOT 8B registers. And, if both Zfinx and Zdinx exist, then you need to accommodate both sizes, don't you?  And, they're different on RV64 vs. RV32. So Zdinx would need to execute 2 separate LW ops on an RV32 compared to a single LD that RV64 to replace a FLD.

2024-02-05 14:36 UTC, davidharrishmc commented
CORE-V Wally will take advantage of the FMA tests as soon as you have them available.

2024-02-06 04:42 UTC, anuani21 commented
I have updated FMA tests for Zfh and Zfinx extension.

2024-02-06 20:43 UTC, davidharrishmc commented
I tried them out and they are working for me.  The f{madd/msub/nmadd/nmsub}_b15-01 tests are not in the PR.  These are the largest set of FMA tests.  Is there a reason they aren't applicable to Zfh?

2024-02-06 23:36 UTC, anuani21 commented
I will check and let you know

On Wed, 7 Feb, 2024, 2:13 am David Harris, ***@***.***> wrote:

> I tried them out and they are working for me. The
> f{madd/msub/nmadd/nmsub}_b15-01 tests are not in the PR. These are the
> largest set of FMA tests. Is there a reason they aren't applicable to Zfh?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1930719795>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3G6FF2UBZHAXKPUE5VIGYTYSKIXPAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZQG4YTSNZZGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-07 04:16 UTC, anuani21 commented
@davidharrishmc, Are you facing any issue while running Zfinx test?

2024-02-07 04:51 UTC, davidharrishmc commented
I don't have hardware support for Zfinx, so I don't know if those tests have any issues.

2024-02-07 05:00 UTC, anuani21 commented
No issues in the test, to check whether it is working fine.

On Wed, 7 Feb, 2024, 10:21 am David Harris, ***@***.***>
wrote:

> I don't have hardware support for Zfinx, so I don't know if those tests
> have any issues.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-1931278951>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3G6FF4ZL4OT5T2S22RRRHLYSMB67AVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZRGI3TQOJVGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-07 06:27 UTC, anuani21 commented
@davidharrishmc, I have updated  f{madd/msub/nmadd/nmsub}_b15-01 tests in the PR.

2024-03-15 04:50 UTC, davidharrishmc commented
The fcvt.h.l tests should only depend on the F and Zfh extensions, as indicated in the test case.

```
RVTEST_CASE(0,"//check ISA:=regex(.*64.*I.*F.*Zfh.*);def TEST_CASE_1=True;",fcvt.h.l_b25)
inst_0:// rs1==x31, rd==f31,rs1_val == 0 and  fcsr == 0 and rm_val == 7  
/* opcode: fcvt.h.l ; op1:x31; dest:f31; op1val:0x0; valaddr_reg:x3;
val_offset:0*8; rmval:dyn; correctval:??; testreg:x2;
fcsr_val: 0*/
TEST_FPIO_OP(fcvt.h.l, f31, x31, dyn, 0, 0, x3, 0*8, x4, x1, x2,ld)
```

However, the TEST_FPIO_OP macro generates a fsd, which requires the D extension.  Therefore, these tests do not run successfully on a RV64IFZfh machine.  

```
0000000080000440 <inst_0>:
    80000440:	0001bf83          	ld	t6,0(gp)
    80000444:	00000113          	li	sp,0
    80000448:	00311073          	fscsr	sp
    8000044c:	d42fffd3          	fcvt.h.l	ft11,t6
    80000450:	00302273          	frcsr	tp
    80000454:	01f0b027          	fsd	ft11,0(ra)
    80000458:	0040b423          	sd	tp,8(ra)
```

It would be better to produce a fsw or fsh in this situation.

2024-03-23 21:48 UTC, allenjbaum commented
I see no further commits that would indicate that the problem David found (tests use D-ext ops on a configuration that only supports F-extension) have been fixed. Has that one been fixed?

As far as I can tell, that "fsd" corresponds to the first parameter of TEST_FPIO_OP ("inst" parameter ) 
but I can't find any instance of "fsd* used anywhere in the repo, so I don't have any idea where it is coming from.

2024-03-23 22:09 UTC, allenjbaum commented
Actually, that "fsd" op corresponds to something after the FPIO macro, but all the FP tests that use the FPIO macro consist of nothing but FPIO macros. the only ops that use FPIO are FCVT ops, and there are no uses of fsd in them, therefore it must be after the FPIO. But, all of those tests end with no further ops. Search for "fsd" shows only tests of fsd, and the don't use FPIO. So, I cannot figure out where that fsd is being generated.

2024-03-24 02:38 UTC, anuani21 commented
@david and @allen ,I will check and get back to you. Sorry for the delay.

On Sun, 24 Mar, 2024, 3:40 am Allen Baum, ***@***.***> wrote:

> Actually, that "fsd" op corresponds to something after the FPIO macro, but
> all the FP tests that use the FPIO macro consist of nothing but FPIO
> macros. the only ops that use FPIO are FCVT ops, and there are no uses of
> fsd in them, therefore it must be after the FPIO. But, all of those tests
> end with no further ops. Search for "fsd" shows only tests of fsd, and the
> don't use FPIO. So, I cannot figure out where that fsd is being generated.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-2016615588>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3G6FFYWEVJWFTSEUNXSE7DYZX4UNAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJWGYYTKNJYHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-25 04:58 UTC, anuani21 commented
@davidharrishmc  and @allenjbaum,

I have updated the test using fsw instead of fsd. I have attached the logs for your reference for fcvt.h.l instruction.

00000000800003ac <inst_0>:
    800003ac:	0001bf83          	ld	t6,0(gp)
    800003b0:	00000113          	li	sp,0
    800003b4:	00311073          	fscsr	sp
    800003b8:	d42fffd3          	fcvt.h.l	ft11,t6
    800003bc:	00302273          	frcsr	tp
    800003c0:	01f0a027          	fsw	ft11,0(ra)
    800003c4:	0040b223          	sd	tp,4(ra)

2024-03-25 15:00 UTC, allenjbaum commented
Would you mind submitting a PR for the bugs you found?

On Mon, Mar 25, 2024 at 6:04 AM David Harris ***@***.***>
wrote:

> This fix to RVTEST_ISA looks good.
>
> There is still an inconsistency between the check ISA lines in
> fcvt.h.l_b25 and _b26. The instruction should depend on RV64, so I think
> the _b25 line should add *RV64 to match _b26.
>
> RVTEST_CASE(0,"//check ISA:=regex(.*I.*F.*Zfh.*);def
> TEST_CASE_1=True;",fcvt.h.l_b25)
> RVTEST_CASE(0,"//check ISA:=regex(.*RV64.*I.*F.*Zfh.*);def
> TEST_CASE_1=True;",fcvt.h.l_b26)
>
> The same applies to fcvt.h.lu_b25.
>
> The check ISA is also wrong (usually has D, always missing RV64) on
> fcvt.l.h*, fcvt.lu.h*
>
> Nevertheless, the incorrect macros are not preventing me from building and
> running the tests. The new tests pass on CORE-V Wally.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-2017965892>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJUIRO7BKKAISLMCCZ3Y2AOHJAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJXHE3DKOBZGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-25 15:06 UTC, davidharrishmc commented
Zfh isn’t in the repo yet, so I don’t know how to do a PR on a PR.  Could you either accept PR367 and I’ll do a PR with these fixes, or anuani could incorporate fixes into PR367?

David

> On Mar 25, 2024, at 8:01 AM, Allen Baum ***@***.***> wrote:
> 
> 
> Would you mind submitting a PR for the bugs you found? 
> 
> On Mon, Mar 25, 2024 at 6:04 AM David Harris ***@***.***> 
> wrote: 
> 
> > This fix to RVTEST_ISA looks good. 
> > 
> > There is still an inconsistency between the check ISA lines in 
> > fcvt.h.l_b25 and _b26. The instruction should depend on RV64, so I think 
> > the _b25 line should add *RV64 to match _b26. 
> > 
> > RVTEST_CASE(0,"//check ISA:=regex(.*I.*F.*Zfh.*);def 
> > TEST_CASE_1=True;",fcvt.h.l_b25) 
> > RVTEST_CASE(0,"//check ISA:=regex(.*RV64.*I.*F.*Zfh.*);def 
> > TEST_CASE_1=True;",fcvt.h.l_b26) 
> > 
> > The same applies to fcvt.h.lu_b25. 
> > 
> > The check ISA is also wrong (usually has D, always missing RV64) on 
> > fcvt.l.h*, fcvt.lu.h* 
> > 
> > Nevertheless, the incorrect macros are not preventing me from building and 
> > running the tests. The new tests pass on CORE-V Wally. 
> > 
> > — 
> > Reply to this email directly, view it on GitHub 
> > <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-2017965892>, 
> > or unsubscribe 
> > <https://github.com/notifications/unsubscribe-auth/AHPXVJUIRO7BKKAISLMCCZ3Y2AOHJAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJXHE3DKOBZGI> 
> > . 
> > You are receiving this because you were mentioned.Message ID: 
> > ***@***.***> 
> > 
> —
> Reply to this email directly, view it on GitHub <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-2018207874>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AR4AA34N4OT4TV6PVRBZ77TY2A325AVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJYGIYDOOBXGQ>.
> You are receiving this because you were mentioned.
>

2024-03-25 15:06 UTC, allenjbaum commented
Oh, and anuani21 - thanks for figuring out what the problem is. 
Now we know we should carefully review this macros as well as the tests.
It is still a puzzle to me that this wasn't caught ages ago.

2024-03-25 16:08 UTC, allenjbaum requested changes
This looks good, and thanks for figuring out what the problem was. I would ask that you back out the changes in the comments however, as the clutter up the diff. We can merge it as soon as that is done.

2024-03-25 16:12 UTC, allenjbaum commented
yes. I want some changes to the PR #367 first though, to back out changes
to the comments.
Those are unnecessary, and clutter up the diff - and will clutter the diff
up again if someone regenerates the tests, so it should ust be left
along (and, yes, I know I can filter out comments fro the diff...)

On Mon, Mar 25, 2024 at 8:06 AM David Harris ***@***.***>
wrote:

> Zfh isn’t in the repo yet, so I don’t know how to do a PR on a PR. Could
> you either accept PR367 and I’ll do a PR with these fixes, or anuani could
> incorporate fixes into PR367?
>
> David
>
> > On Mar 25, 2024, at 8:01 AM, Allen Baum ***@***.***> wrote:
> >
> >
> > Would you mind submitting a PR for the bugs you found?
> >
> > On Mon, Mar 25, 2024 at 6:04 AM David Harris ***@***.***>
> > wrote:
> >
> > > This fix to RVTEST_ISA looks good.
> > >
> > > There is still an inconsistency between the check ISA lines in
> > > fcvt.h.l_b25 and _b26. The instruction should depend on RV64, so I
> think
> > > the _b25 line should add *RV64 to match _b26.
> > >
> > > RVTEST_CASE(0,"//check ISA:=regex(.*I.*F.*Zfh.*);def
> > > TEST_CASE_1=True;",fcvt.h.l_b25)
> > > RVTEST_CASE(0,"//check ISA:=regex(.*RV64.*I.*F.*Zfh.*);def
> > > TEST_CASE_1=True;",fcvt.h.l_b26)
> > >
> > > The same applies to fcvt.h.lu_b25.
> > >
> > > The check ISA is also wrong (usually has D, always missing RV64) on
> > > fcvt.l.h*, fcvt.lu.h*
> > >
> > > Nevertheless, the incorrect macros are not preventing me from building
> and
> > > running the tests. The new tests pass on CORE-V Wally.
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-2017965892>,
>
> > > or unsubscribe
> > > <
> https://github.com/notifications/unsubscribe-auth/AHPXVJUIRO7BKKAISLMCCZ3Y2AOHJAVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJXHE3DKOBZGI>
>
> > > .
> > > You are receiving this because you were mentioned.Message ID:
> > > ***@***.***>
> > >
> > —
> > Reply to this email directly, view it on GitHub <
> https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-2018207874>,
> or unsubscribe <
> https://github.com/notifications/unsubscribe-auth/AR4AA34N4OT4TV6PVRBZ77TY2A325AVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJYGIYDOOBXGQ>.
>
> > You are receiving this because you were mentioned.
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/367#issuecomment-2018220095>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJRFC5UO6K5IBK4ZKP3Y2A4O7AVCNFSM6AAAAAAZ37DUD6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJYGIZDAMBZGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-25 22:05 UTC, allenjbaum approved these changes
This unneccessarily (in my opinion, anyway) edits comments - but I don't think that will cause future problem. It also has a simple fix for the issues that were seen. We may want further tests in the future to more carefully look at corner cases for better coverage, but this is at a minimum a good start

2024-03-25 22:25 UTC, allenjbaum commented
sigh: as usual, we have a conflict with the changelog version. It needs to be updated.
Note that in future, all PRs should be filed against the dev branch, the dev branch should not be checking for changelog version numbers, and maintainers will be responsible for updating the union of changelogs for all the PRs included in that version of the dev branch

2024-03-26 04:45 UTC, anuani21 commented
@allenjbaum, I have updated the changelog file. Please have your review and let us know if more information would help.

Hereafter, I will raise the PR with target branch as dev.

2024-03-26 05:41 UTC, allenjbaum approved these changes
This fixes the problem, and the previous fixes the earlier problem of specifying D support for an extension that doesn't need it.

2024-03-26 20:07 UTC, merged

2024-04-02 21:33 UTC, stnolting commented
Just one question about this: `Zfinx` is currently only supported for `rv64` machines, right?! 🤔

(there is a `rv64i_m/Zfinx` testcases folder but no `rv32i_m/Zfinx` testcases folder)