Add unratified Zabha extension
riscv-non-isa/riscv-arch-test pull request #402
Opened 2023-10-30 22:31 UTC by ved-rivos

<FOR DOC UPDATES FILL ONLY DESCRIPTION AND RELATED ISSUES SECTION AND REMOVE THE OTHERS>

## Description

Add tests for Zabha extension specified in https://github.com/riscv/riscv-zabha

### Related Issues

CTG: https://github.com/riscv-software-src/riscv-ctg/pull/88
Config: https://github.com/riscv-software-src/riscv-config/pull/152

### Ratified/Unratified Extensions

- [ ] Ratified
- [X ] Unratified

### List Extensions

https://github.com/riscv/riscv-zabha

### Reference Model Used

- [X ] SAIL
- [ X] Spike
- [ ] Other - < SPECIFY HERE >

### Mandatory Checklist:

  - [ X] All tests are compliant with the test-format spec present in this repo ?
  - [ X] Ran the new tests on RISCOF with SAIL/Spike as reference model successfully ?
  - [ ] Ran the new tests on RISCOF in [coverage mode](https://riscof.readthedocs.io/en/stable/commands.html#coverage)
  - [ ] Link to Google-Drive folder containing the new coverage reports ([See this](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/CONTRIBUTION.md#uploading-test-stats) for more info): < SPECIFY HERE >
  - [ ] Link to PR in RISCV-ISAC from which the reports were generated : < SPECIFY HERE > 
  - [ X] Changelog entry created with a minor patch

### Optional Checklist:

  - [ ] RISCV-V CTG PR link if tests were generated using it : < SPECIFY HERE >
  - [ ] Were the tests hand-written/modified ?
  - [ ] Have you run these on any hard DUT model ? Please specify name and provide link if possible in the description
  - [ ] If you have modified arch\_test.h Please provide a detailed description of the changes in the Description section above.

2025-05-23 05:58 UTC, allenjbaum requested changes
It appears that these tests are always storing into byte (or halfword) 0 of the signature area. These tests need to be rewritten to ensure that every byte (or halfword) offset within a word used, and that has to be added to the coverpoints. This willl likely require a new RTEST_AMO_OP macro that has an offset parameter, and a new coverage metric that ensures that all 0...3 or 0..7 offsets are used for .b ops in RV32/64, and 2*0..1 and 2*0..3 offsets are used for .h ops

2025-05-23 10:31 UTC, ved-rivos commented
Why does it matter that the signature area has holes ?

2025-05-23 17:41 UTC, allenjbaum commented
It isn't that the signature area has holes. It's that you're testing
something whose previous implementation was words or double, and now you're
writing halfwords or bytes, and you're only accessing the LSBs of each
word/double, never testing any other offset. That's a huge coverage hole.
 You're also not testing unaligned accesses, even within a word.

On Fri, May 23, 2025 at 3:31 AM Ved Shanbhogue ***@***.***>
wrote:

> *ved-rivos* left a comment (riscv-non-isa/riscv-arch-test#402)
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/402#issuecomment-2903999950>
>
> Why does it matter that the signature area has holes ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/402#issuecomment-2903999950>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJSRJHT5JZI4J4Z572D2732H7AVCNFSM6AAAAAB5X2N4AOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDSMBTHE4TSOJVGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-05-23 17:55 UTC, ved-rivos commented
I dont understand the comment  about previous implementation. Zabha adds new instructions to do byte and halfword atomics. Unaligned accesses must be tested by an ACT for Zama16b. By default Zabha will raise an access-fault or address-misaligned exception if its not naturally aligned.

2025-05-23 18:16 UTC, allenjbaum commented
Yes, by default Zabha will raise an access fault.
Prove it by writing a test that shows that it will fault , and fault
correctly (correct cause/epc/tval).
But the other part is: show that Zabha will do the correct thing if it
accesses any naturally aligned offset within a word or double, not just
offset 0.

On Fri, May 23, 2025 at 10:55 AM Ved Shanbhogue ***@***.***>
wrote:

> *ved-rivos* left a comment (riscv-non-isa/riscv-arch-test#402)
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/402#issuecomment-2905357500>
>
> I dont understand the comment about previous implementation. Zabha adds
> new instructions to do byte and halfword atomics. Unaligned accesses must
> be tested by an ACT for Zama16b. By default Zabha will raise an
> access-fault or address-misaligned exception if its not naturally aligned.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/402#issuecomment-2905357500>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJUOX2SWE253B7EOK6D275OJ7AVCNFSM6AAAAAB5X2N4AOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDSMBVGM2TONJQGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-05-23 18:43 UTC, ved-rivos commented
The access fault on misaligned AMO should be a separate test - not unique to Zabha. We will need to enhance all AMO and LR/SC tests to cover the misaligned case. I will try to send a PR for that separately.

For the second one I will how to cover other offsets. This PR has been sitting around for close to two years and I will need to reconstruct its sources to update it.

2025-05-23 23:16 UTC, allenjbaum commented
That's fine - make them separate tests then- but these still need to try
examples of tests whose low 3 address bits are not 000.
The load/store tests do that and more, and this with its arithmetic and
atomic capabilities, need even more testing.

On Fri, May 23, 2025 at 11:43 AM Ved Shanbhogue ***@***.***>
wrote:

> *ved-rivos* left a comment (riscv-non-isa/riscv-arch-test#402)
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/402#issuecomment-2905460360>
>
> The access fault on misaligned AMO should be a separate test - not unique
> to Zabha. We will need to enhance all AMO and LR/SC tests to cover the
> misaligned case. I will try to send a PR for that separately.
>
> For the second one I will how to cover other offsets. This PR has been
> sitting around for close to two years and I will need to reconstruct its
> sources to update it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/402#issuecomment-2905460360>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJRVEXWTKBGZ7B3KVJL275T6ZAVCNFSM6AAAAAB5X2N4AOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDSMBVGQ3DAMZWGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-05-23 23:25 UTC, ved-rivos commented
Agree this is a hole in the current AMO suite in ACT that needs improvement.
They need to test not just lower 3 bits not being 0 but for double-work-amocas test lower lower 4 bits

2025-05-24 00:18 UTC, allenjbaum commented
Yes, you are correct; that means that the .W versions have to test  the
upper half of a double. Just add a comment in an open issue to that effect



On Fri, May 23, 2025 at 4:25 PM Ved Shanbhogue ***@***.***>
wrote:

> *ved-rivos* left a comment (riscv-non-isa/riscv-arch-test#402)
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/402#issuecomment-2906012080>
>
> Agree this is a hole in the current AMO suite in ACT that needs
> improvement.
> They need to test not just lower 3 bits not being 0 but for
> double-work-amocas test lower lower 4 bits
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riscv-non-isa/riscv-arch-test/pull/402#issuecomment-2906012080>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPXVJQR3PWI3NMGHLO52SL276U7FAVCNFSM6AAAAAB5X2N4AOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDSMBWGAYTEMBYGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2026-01-23 06:02 UTC, UmerShahidengr commented
@ved-rivos thank you so much for your work on this one. We are switching over to our new framework for Certification, and new tests on Zabha will be added based on the new template. Since there has been no updates since the last time changes were requested, we will close this one as soon as the new tests will be available.

2026-01-28 15:56 UTC, jordancarlin commented
@ved-rivos #874 adds Zabha and Zacas tests to ACT4. Closing this now, but thanks for all of your work on it. Feel free to review #874 if you'd like.

2026-01-28 15:56 UTC, closed without merging