Atomic extension LR/SC tests and coverpoints
riscv-non-isa/riscv-arch-test pull request #439
Opened 2024-02-26 11:46 UTC by muhammad-maarij-zeeshan

## Description
> Adds tests for LR/SC instructions in Atomic (A) Extension. The following [test plan](https://docs.google.com/spreadsheets/d/1kYHKfZmSDmKRlSjKyRu-vJVfNVUDYSDgLT42q_Obbxw/edit?usp=sharing) has been implemented and the test have been written for both RV32 and RV64. The asssembly tests have been developed by [Muhammad Maarij Zeeshan](https://github.com/muhammad-maarij-zeeshan) and the coverpoints are devloped by [Muhammad Hammad Bashir](https://github.com/MuhammadHammad001).

### Related Issues
> NA

### Ratified/Unratified Extensions
- [x] Ratified
- [ ] Unratified

### List Extensions
> Atomic Extension (A)

### Reference Model Used
- [x] SAIL
- [ ] Spike
- [ ] Other - < SPECIFY HERE >

### Mandatory Checklist:
  - [x] All tests are compliant with the test-format spec present in this repo ?
  - [x] Ran the new tests on RISCOF with SAIL/Spike as reference model successfully ?
  - [x] Ran the new tests on RISCOF in [coverage mode](https://drive.google.com/drive/folders/14LSkJ1vH9ygq1qCN95nIsEv80CUjoIpg?usp=sharing)
  - [x] Link to Google-Drive folder containing the new [coverage reports](https://drive.google.com/drive/folders/136KrrsVS7snWDmYWznggU60gc9lmiuRO?usp=sharing)
  - [ ] Link to PR in RISCV-ISAC from which the reports were generated : < SPECIFY HERE >
  - [x] Changelog entry created with a minor patch

### Optional Checklist:
  - [ ] RISCV-V CTG PR link if tests were generated using it : < SPECIFY HERE >
  - [ ] Were the tests hand-written/modified ?
  - [ ] Have you run these on any hard DUT model ? Please specify name and provide link if possible in the description
  - [ ] If you have modified arch\_test.h Please provide a detailed description of the changes in the Description section above.

2024-04-02 14:12 UTC, UmerShahidengr commented
@allenjbaum please review this PR when you are free. It is completed from our side but it has been stalled for a few weeks

2024-04-08 20:38 UTC, davidharrishmc commented
A few thoughts reviewing the PR visually.

I don't see these tests writing to signature memory.  How do we know if they failed or succeeded?

There are no lr.w and sc.w instructions tested on RV64, even though the ISA should support these.

Many of the tests try to write a 0 value to memory to prove that memory changed.  0 is special number and might have been written by an incorrect implementation.  Would it be safer to write a random number rather than 0?

2024-04-10 06:20 UTC, allenjbaum requested changes
As with all test that involve storing to  memory, the write to memory should either be directly to the signature area, or should be re-read from whereever it is stored and written to the signature region. Storing directly to the signature area is the preferred method. 
In addition, the store conditional updates a destination register, and that must be stored into the signature as well. The RVTEST_SIGUPD macro should be used (unless you are storing non contiguous addresses)
These tests only load/store from the data region, which isn't acceptable. Storing a changing value (rather than zero)  is preferred (e.g. an incrementing value is fine).

A constrained loop must " exclude loads, stores, backward jumps, taken backward branches, JALR, FENCE, and SYSTEM instructions" and the compressed extension equivalents. Because we can't predict whether an implementation will pass or fail with an unconstrained loop, we are forced to only test with those constraints .These tests will need to be rewritten to exclude those and also be 16 instructions long ( I think those 16 instructions include both the LR and the SC, and any backwards branch for retry - and we shouldn't test anything longer than that because implementations are allowed to succeed.  Also, we shouldn't expect that SCs to a different address or length (in the same reservation set) will fail - they are allowed to succeed, so can't test those either.


Note that after each loop, the  SC should attempt to store into a different signature word, as should the Rd register.  I think this means that if the loop contains a store to something outside the reservation set, we don't know if will pass or fail, so we can't test that - but we can test something that is to the same reservation set and see that it fails.
Let's meet and talk about these tests

2024-12-30 17:06 UTC, UmerShahidengr commented
These tests need rewriting, will be assigned to somebody soon.

2026-02-24 16:31 UTC, jamesbeyond commented
ACT repository have been updated `act4` as the default branch,  ACT4 have the tests for Atomic extension LR/SC covered already. So this PR can be closed. Thanks for your contribution.

2026-02-24 16:31 UTC, closed without merging