Fixed reversed order of Zicboz and Zicsr in macros for cbo.zero
riscv-non-isa/riscv-arch-test pull request #473
Opened 2024-06-11 19:50 UTC by davidharrishmc

<FOR DOC UPDATES FILL ONLY DESCRIPTION AND RELATED ISSUES SECTION AND REMOVE THE OTHERS>

## Description

> Provide a detailed description of the changes performed by the PR.

### Related Issues

> Please list all the issues related to this PR. Use NA if no issues exist

### Ratified/Unratified Extensions

- [ ] Ratified
- [ ] Unratified

### List Extensions

> List the extensions that your PR affects. In case of unratified extensions, please provide a link to the spec draft that was referred to make this PR.

### Reference Model Used

- [ ] SAIL
- [ ] Spike
- [ ] Other - < SPECIFY HERE >

### Mandatory Checklist:

  - [ ] All tests are compliant with the test-format spec present in this repo ?
  - [ ] Ran the new tests on RISCOF with SAIL/Spike as reference model successfully ?
  - [ ] Ran the new tests on RISCOF in [coverage mode](https://riscof.readthedocs.io/en/stable/commands.html#coverage)
  - [ ] Link to Google-Drive folder containing the new coverage reports ([See this](https://github.com/riscv-non-isa/riscv-arch-test/blob/main/CONTRIBUTION.md#uploading-test-stats) for more info): < SPECIFY HERE >
  - [ ] Link to PR in RISCV-ISAC from which the reports were generated : < SPECIFY HERE > 
  - [ ] Changelog entry created with a minor patch

### Optional Checklist:

  - [ ] RISCV-V CTG PR link if tests were generated using it : < SPECIFY HERE >
  - [ ] Were the tests hand-written/modified ?
  - [ ] Have you run these on any hard DUT model ? Please specify name and provide link if possible in the description
  - [ ] If you have modified arch\_test.h Please provide a detailed description of the changes in the Description section above.

2024-06-11 19:53 UTC, davidharrishmc commented
Note that Sail does not yet support cbo.zero, so Sail throws an illegal instruction exception when attempting to simulate it during riscof compilation.  Consequently I have been unable to full test this.  However, it should fix the problem Tim Hutt raised about the commit.

https://github.com/riscv-non-isa/riscv-arch-test/commit/e3c5471f58573ea99cd282197251e7c453ba1696#r143001732

2024-06-12 06:28 UTC, Timmmm requested changes
Thanks!

I have a PR to add cbo.zero support to Sail here if you want to test it:

https://github.com/riscv/sail-riscv/pull/455

However I'd say it's not necessary for you to test it - I made the same changes locally and it selects the test now & passes. (I would have made a PR but you were faster than our PR approval process!)

2024-06-12 06:28 UTC, Timmmm commented on riscv-test-suite/rv32i_m/CMO/src/cbo.zero-01.S
> +RVTEST_ISA("RV32IZicboz_Zicsr")
This is inconsistent with the other file. I couldn't work out exactly what this macro does but they should probably be consistent at least.

2024-06-12 09:17 UTC, UmerShahidengr commented on riscv-test-suite/rv32i_m/CMO/src/cbo.zero-01.S
> +RVTEST_ISA("RV32IZicboz_Zicsr")
This macro is used to select the test from the test pool, both combinations `RV32IZicsr_Zicboz` and `RV32IZicboz_Zicsr` are doing the same thing, so this order does not matter for the case of `Zicboz`. I would recommend updating the RVTEST_ISA string for RV64 test as well. It will be good to go after updating the same line in RV64 variant of the test.

2024-06-12 09:21 UTC, UmerShahidengr approved these changes

2024-06-12 09:21 UTC, UmerShahidengr commented on riscv-test-suite/rv32i_m/CMO/src/cbo.zero-01.S
> +RVTEST_ISA("RV32IZicboz_Zicsr")
I have done the modifications, now this one is good to go.

2024-06-12 09:22 UTC, UmerShahidengr commented
@jamesbeyond please have a look at it, this one is good to go, so you may merge this one

2024-06-12 10:23 UTC, Timmmm approved these changes
Thanks!

2024-06-12 10:34 UTC, davidharrishmc commented on riscv-test-suite/rv64i_m/CMO/src/cbo.zero-01.S
I added Zicsr to the RV64 cbo.zero RVTEST_ISA string for consistency with the other tests per @UmerShahidengr 's comment.

I'm not the author of cbo.  It appears that the cbo tests don't use CSRs and that the Zicsr would likely be unnecessary.  I believe somebody from my team had experimented with that months ago and presumably removed the Zicsr in just this case, but I agree that it is better to be consistent.  It's hard to envision a system with caches but no CSRs, so Zicsr is likely harmless, and if the tests are ever generalized to non-machine mode, Zicsr will be nessary to support menvcfg and the other modes.

@liweiwei90 was the original author of PR #226 with cbo.zero tests.  I will defer to the author if they decide to remove Zicsr from cbo.zero at a later point. If so, I think it should come out of RVTEST_ISA and RVTEST_CASE for both rv32i_m and rv64i_m.

2024-07-01 16:09 UTC, jamesbeyond approved these changes
LGTM

2024-07-01 16:10 UTC, merged