ACTs and coverage points for machine mode software and timer interrupts
riscv-non-isa/riscv-arch-test pull request #567
Opened 2024-11-21 15:46 UTC by Ali-Faraz-10xe

<FOR DOC UPDATES FILL ONLY DESCRIPTION AND RELATED ISSUES SECTION AND REMOVE THE OTHERS>

## Description

This pull request introduces tests and covergroups to verify machine mode software and timer interrupts. The tests and covergroups were developed following the guidelines outlined in the [Test Plan](https://docs.google.com/spreadsheets/d/1rwjSTbxKiXTDydAdFAE_o7mez_hcFj9a-9d3dXRVc4s/edit?usp=sharing)

### Related Issues

This pull request relies on the changes in the following PRs for full functionality and compatibility:
1. [Interrupt Coverage Support](https://github.com/riscv-non-isa/riscv-arch-test/pull/558) 
2. [Print MTI value upon hart update for machine timer interrupt visibility](https://github.com/riscv/sail-riscv/pull/620) 

### Ratified/Unratified Extensions

- [x] Ratified
- [ ] Unratified

### List Extensions

N/A

### Reference Model Used

- [x] SAIL
- [ ] Spike
- [ ] Other - < SPECIFY HERE >

### DUT Model Used

- [ ] SAIL
- [x] Spike
- [ ] Other - < SPECIFY HERE >

### Mandatory Checklist:

  - [x] All tests are compliant with the test-format spec present in this repo ?
  - [x] Ran the new tests on RISCOF with SAIL/Spike as reference model successfully ?
  - [x] Ran the new tests on RISCOF in [coverage mode](https://riscof.readthedocs.io/en/stable/commands.html#coverage)
  - [x] Link to Google-Drive folder containing the new coverage reports [available here](https://drive.google.com/file/d/1bgrGzx1_Zpoo4MCtk-YZ-WU2SIZjZzzm/view?usp=drive_link)
  - [x]  Link to PR in RISCV-ISAC from which the reports were generated [available here](https://github.com/riscv-non-isa/riscv-arch-test/pull/558)

### Optional Checklist:

  - [x] Were the tests hand-written/modified ?

2024-12-04 05:31 UTC, allenjbaum requested changes
In general, equations with constants (e.g. mip>>3 & 0x1!= 0x1) are not satisfactory. What would be satisfactory would be ((mip & MIP_MSIP)==0), where MIP_MSIP is #defined -   and you don't even have to define it yourself because it is already defined in encoding.h which is #included. Note that this applies of almost CSR fields . The comments are quite appreciated, on the other hand.

2024-12-04 05:35 UTC, allenjbaum commented on coverage/header_file.yaml
> + MTIME_BASE: 0x0200bff8
Where did these default values come from? There is a model defined variables, which should be named RVMODEL_MSIP_BASE, etc to be consistent with all other model defined variables.

2024-12-04 05:41 UTC, allenjbaum commented on riscof-plugins/rv32/sail_cSim/env/model_test.h
> +    li   t2, 0x2000000                ;\
1. using constants is prohibited; use the value you defined above: MSIP_MBASE
2. use of li is prohibited in tests; use LI(rd, mnemonic_value) instead.
These apply to ALL li ops in all tests, not just this one

2024-12-09 13:33 UTC, Ali-Faraz-10xe commented on coverage/header_file.yaml
> + MTIME_BASE: 0x0200bff8
These are standard RISC-V CLINT (Core-Local Interrupt) base addresses, which also used in the Sail model. MSIP_BASE and others are now replaced with the RVMODEL_MSIP_BASE etc in all ACTs.

2024-12-09 13:36 UTC, Ali-Faraz-10xe commented on riscof-plugins/rv32/sail_cSim/env/model_test.h
> +    li   t2, 0x2000000                ;\
Yes, it is replaced in all plugins and proper macro is used now.

2025-02-22 08:30 UTC, allenjbaum requested changes
Almost all tests need to initialize MIP.MSIP/MTIP before doing anything else.
The MAX_VALE should be renamed TEST_VALUE, since it isn't a max value at all.
I think you could combine a lot of the 32 and 64b tests, except for the cases that need to write all 64bits of MTIME and MTiMECMP (which I would do with a macro to and read them differently depending on XLEN)

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +        SREG    T4, 3*REGWIDTH(T1)      // save 4th sig value, (xie)
XIE should not be saved, as an interrupt doesn't affect its value.  The comments before label common_\_MODE__()handler give number&names of the variables that interrupts save in the interrupt signature:
Vect+mode, xcause, xip, IntID - and only if hypervisor is implemented, tvalt2 and tinst.

Basically, do not modify arch_test.h without consulting me first

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/env/encoding.h
> +#define MIE_SSIP            (1 << IRQ_S_SOFT)
Hmm - these should already be defined in the master copy of encoding.h We need to make sure that the latest copy is automatically pulled in (not a problem for this PR)

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +#ifndef MSIP_BASE
I'm not sure we actually want to default this; we should force models to declare it and raise an error if they don't (and they're testing interrupts...)

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +       	nop
1. you have a noop after each write. Why? These MMIO addresses should all be written in order.
There shouldn't be an interrupt until the last one is written - but it may not be immediately (the next instruction).
2. Also note: there may be no guarantee that an interrupt will occur upon completion of the op that set the MIP_MIE bit. The test must take that into account

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +    	LI(a1,    MIE_MSIP)
Note that you could simply LI(a1, MIE_MSIP+MIE_MTIP) instead of loading 2 consts and ORing them

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +    	LI(a1,    MIE_MSIP)
Note that you're enabling 2 interrupts simultaneously, and both will be taken, one after the other. So there will be two trap signatures, and I believe they will be back to back - no instructions will be executed between the xret and entry to the handler

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-TIMER-INTR.S
> +	csrrs a4, CSR_MIP, x0
note that MIP is already set from the previous test, so the interrupt might occur before you set it again, which will mess up what you're trying to test for

2025-02-22 08:30 UTC, allenjbaum commented on coverage/rv32_m_interrupts.cgf
> +      '(((mip >> 3)  &  0x1) != 1)' : 0 # Ensures Machine Software Interrupt Pending (MSIP) bit cannot be modified by write operations, maintaining read-only protection.
Do not use constants in the coverage equations; use only #defined variables (most of which are in already in encoding.h). And for this don't shift, and, cmp with 1, just and with a mask and compare to zero

2025-02-22 08:30 UTC, allenjbaum commented on coverage/rv32_m_interrupts.cgf
> +      '(((mip >> 3)  &  0x1) != 1)' : 0 # Ensures Machine Software Interrupt Pending (MSIP) bit cannot be modified by write operations, maintaining read-only protection.
This applies pervasively to all your constants (except zero...)

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +    	LI(a2,    MIE_MTIP)
Why aren't you simply LI(a1, MIE_MSIP+MTIP)?
Not sure if this is guaranteed to make  both interrupts to occur simultaneously. (probably though).
I don't think the trap handler will clear all interrupts, just the highest priority one.
That means you'll get another interrupt as soon as you return from the trap handler. 
That can break this code, unless you have extra noops after setting MIE. 
It also requires you to allocate space for 2 interrupt signatures.

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +       	SREG a3, 0(t0)
This may cause an immediate interrupt, because MIE_MSIP is unitialized. 
You need to clear it before you set MSTATUS_MIE.

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-SOFTWARE-INTR.S
> +main:
This sets MSTATUS_MIE before clearing MIP_MSIP. The value of MIP_MSIP is not guaranteed to be zero atreset

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-TIMER-INTR.S
> +main:
This needs to initialize MIE.MTIP to zero before setting MSTATUS.MIE
Note that there will be a delay between setting MTIME and MTIMECMP and the interrupt appearing in MIP that could be longer than the amount of time between them and the setting/clring the MIE.MTIP and MSTATUS.MIE bits. You need to insert a delay after writing MTIME and MTIMECMP 
9and the delay amount should be provided by the DUT as the #cycles from writing those register until the MIP.MTIP bit gets set.)

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-TIMER-INTR.S
> +main:
Also: you're testing when mtime is < mtimecmp and when it is equal. - I on't see how you can guarantee that since mtime is constantly being updated at an unknown rate. You have to is write MTIMECMP with the value read from MTIME (when MIE and MIP.MTIP are enabled - and you need to do it before test 3 AND before test 4

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-MSIP-FUNCTIONALITY.S
> -	SREG zero, 0(x5)
The trap handler will clear the MSIP bit before returning, else it will just keep reinterrupting.
And it already saves it into the signature

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-MTIME-LENGTH.S
> +
You aren't testing that all 64 bits are writable, just that the lower 32bits, and not testing that MTIME could count and overflow the low 32b or that it could wrap around from -1 to zero.

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-MTIME-LENGTH.S
> +// This test verifies the 64-bit precision of machine timer (mtime) and
As before, the > condition is easy to check, the = condition is harder, since it is always counting. By the time you check the MIP bit, it could have already counted

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/DIS-GLB-MIE.S
> +  	.align	2
you also need to initialize MIP.MSIP before all this as it's not initialized at reset.

2025-02-22 08:30 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-MTIP-FUNCTIONALITY.S
> +	csrrc x0, CSR_MSTATUS, a5
also need to initialize MIP.MTIP.  I'm not going to add this comment anymore, all the tests need to do this (or I'm missed where it is initialized)

2025-03-27 15:49 UTC, UmerShahidengr commented on riscv-test-suite/env/encoding.h
> +#define MIE_SSIP            (1 << IRQ_S_SOFT)
I have synced up the latest copy of encoding.h with this one

2025-03-27 15:52 UTC, UmerShahidengr commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +       	SREG a3, 0(t0)
This test is checking Interrupt priority resolution mechanism i.e,  software interrupt precedence over timer interrupts. So, this method is correct for checking that test case I think

2025-03-27 15:53 UTC, UmerShahidengr commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +    	LI(a2,    MIE_MTIP)
Agree. this change is required @Ali-Faraz-10xe , can you please do it immediately so that it gets approved?

2025-04-02 06:14 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +        srl     T2, T2, T3              // Move interrupt delegation to LSB
Why do you move it to LSB, clr all but LSB, then beq, rather than move it MSB and bge?

2025-04-03 02:32 UTC, Ali-Faraz-10xe commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +       	nop
After each write, noops are added for a reason. If any implementation doesn't support/implement these memory-mapped registers, then there will be a series of exceptions because of each write, and the test will take a long time to fail/end (as the test will enter again and again into the trap handler when resolving one exception). So noops will help to fail the test in this case since different signatures will be saved in the reference model results and DUT result, hence the comparison will fail.

2025-04-03 03:16 UTC, Ali-Faraz-10xe commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +    	LI(a2,    MIE_MTIP)
Thanks for highlighting this important aspect. I have now changed the test flow by enabling the global interrupt bit (MSTATUS_MIE) after both interrupts are in pending state (MIP_MSIP = 1, MIP_MTIP = 1) and both are enabled locally. This way we guarantee that both interrupts occur simultaneously. The space for 2 interrupt signatures is already allocated. Also, I am going to follow the suggested way of enabling register bits like 'LI(a1, MIE_MSIP+MIE_MTIP)' in all tests. Thanks :)

2025-04-03 08:02 UTC, Ali-Faraz-10xe commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-SOFTWARE-INTR.S
> +main:
you are correct that the value of MIP_MSIP is not guaranteed to be zero at reset, that's why we are first clearing the any pending software interrupt at line no 74, and then start the actual test.

2025-04-03 19:48 UTC, Ali-Faraz-10xe commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-SOFTWARE-INTR.S
> +
@UmerShahidengr this new change causes the coverage to drop to 25% for this test. Upon further investigation, I see there are no software interrupt being generated in both SAIL and DUT.

2025-04-10 11:23 UTC, alifaraz-10xe commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-SOFTWARE-INTR.S
> +
Issue fixed! You have deleted one code line by mistake which results in coverage to drop down.

2025-04-15 11:38 UTC, Ali-Faraz-10xe commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +    	LI(a1,    MIE_MSIP)
That's correct. No instructions is executing between the xret and entry to the handler

2025-04-15 11:42 UTC, alifaraz-10xe commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-MSIP-FUNCTIONALITY.S
> -	SREG zero, 0(x5)
The trap handler is clearing the MSIP bit before returning, hence test is ending properly!

2025-04-15 11:46 UTC, Ali-Faraz-10xe commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/DIS-GLB-MIE.S
> +  	.align	2
Done!

2025-04-18 13:20 UTC, UmerShahidengr commented on riscv-test-suite/env/arch_test.h
> +        SREG    T4, 3*REGWIDTH(T1)      // save 4th sig value, (xie)
It has been done already, so I am resolving this one

2025-04-18 13:20 UTC, UmerShahidengr commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +#ifndef MSIP_BASE
It will be removed from all tests 
CC: @Ali-Faraz-10xe

2025-04-18 13:23 UTC, UmerShahidengr commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-TIMER-INTR.S
> +	csrrs a4, CSR_MIP, x0
RVMODEL_CLR_MTIMER or _MSW_INT has been added on top of every test file, so this comment has also been resolved

2025-04-18 13:23 UTC, UmerShahidengr commented on coverage/rv32_m_interrupts.cgf
> +      '(((mip >> 3)  &  0x1) != 1)' : 0 # Ensures Machine Software Interrupt Pending (MSIP) bit cannot be modified by write operations, maintaining read-only protection.
Already done. So marking this one as resolved

2025-04-18 13:27 UTC, UmerShahidengr commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-TIMER-INTR.S
> +main:
@allenjbaum, This is not something that can be done as fixed delay, do we need to define a new RVMODEL macro for this purpose?

2025-04-18 13:28 UTC, UmerShahidengr commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-MTIME-LENGTH.S
> +
This test has to be rewritten, it is not complete.

2025-04-18 14:19 UTC, Ali-Faraz-10xe commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +#ifndef MSIP_BASE
Done!

2025-04-29 11:21 UTC, UmerShahidengr approved these changes, later dismissed
All requested changes have been done

2025-05-09 06:29 UTC, allenjbaum requested changes
This is the first batch of overall changes that are needed. I'll come back and do another review when these are fixed (I haven't made it all the way through yet.

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +        nop	                // if mideleg is not used and trap occur
You need to document the reason for this. This is setting up the trap handler to take an exception whenever it interrupts into Smode (because it can't read the mideleg CSR that caused it to go to Smode?) 
The problem here is that the trap signature for an illegal instruction won't store mideleg - so the test can never tell whether mideleg was set or not. It would be best to have the test (not the trap handler) explicitly store mideleg whenever it changes it, and avoid the extra trap.

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +        nop
Why is there a nop here? This shouldn't ever trap. Also: you're storing individual bits from Xstatus, XIE, and XIP; you should collect the 3 bits and store them in the first signature entry, (label  sv_\__MODE__\()vect, the first word of the signature entry; there are lots of free bits in that entry. This avoids changing the size of the interrupt trap signature entry. That size is pre-calculated, is used to update the trap signature pointer, and is stored in this entry.  Changing the size introduces a bug because the pointer is pre-incremented with it, and the next trap will overwrite the extra word of this entry.

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +       	nop
Not, exactly. IF you jump to an Mmode test, and any of these (architecturally mandated, vendor provided) addresses don't exist, it will trap, write an exception trap signature, and return, skipping the next instruction. It won't trap over and over, it will (in this case of 4 sequential writes failing) trap at most twice. Even if it traps only once, that will be enough to cause a signature miscompare.  IF it traps too many times (more than you expect and have allocated in the signature region), then it will safely abort the test because the handler checks to see if you've overrun that trap signature area, so its safe even if it keeps writing those addresses over and over in different test cases.

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +       	SREG a3, 0(t0)
Ah, OK. but: 
First, I don't think there is an architecturally defined value of what value a write to MSIP_BASE will cause an interrupt.  That's why there is an RVMODEL_SET_MSW_INT macro. Use it.
Second: You can get away without using RVMODEL_SET_MTIMER_INT - but to be consistent, you should use that also. If makes it much easier to understand the code.

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-SOFTWARE-INTR.S
> +
Ah, I think we need to define these in the default plug-ins for spike and Sail, but if you have your own DUT you'll have to define it in your rvmodel_test.h file.

2025-05-09 06:29 UTC, allenjbaum commented on coverage/m_interrupts/rv32_m_interrupts.cgf
> +# Confirms Machine Interrupt Pending (MIP) register remains read-only
I'm not sure that these coverpoints will tell you anything. This checks to see that mip.[MSIP,MTIP,MEIP] was ever !=1 . But, it will never be 1 because that tests bit0 only, and it needs to test the appropriate bit posiition.  In any case, don't you need to knwo that a write of that specific bit was attempted? This coverpoint be hit even if you don't actually write the CSR bit to 1, but write some other CSR or some other bit.

Also, you need to define a function that checks whether a bit of a CSR has value 1 or 0, so you don't have to write (csrname & ${fieldmask} == ${fieldmask};  e.g. csrbit1(mip,fieldname) and csrbit0(mip,fieldname) for ==0

2025-05-09 06:29 UTC, allenjbaum commented on coverage/m_interrupts/rv32_m_interrupts.cgf
> +# This coverpoint used to validate the 32-bit precision of machine timer (mtime) and timer compare (mtimecmp) register if MTIP hit for the 4 times
mtime & mtimecmp are each is logically 64 bit registers; you need to also check mtimeh and mtimecmph.
I don't understand  hitting mtip 4 times though - explain.

2025-05-09 06:29 UTC, allenjbaum commented on riscof-plugins/rv32/sail_cSim/env/model_test.h
> +#define RVMODEL_SET_MTIMER_INT          ;\
I don't think this will always work if you don't also update MTIME_BASE+4 and MTIMECMP_BASE+4.
Also, you disabled the clr mtime_int routine, and I think you need that because you don't know what the reset value will be.

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +        andi    T4, T4, 0b10001                 // mask xIE and xPIE
1. use mnemonics, not constants
2. this doesn't work because xstatus.yIE  and yPIE are at different bit positions depending on mode y that it trapped from
3. Why not save yourself the trouble and just look the lower 8 bits, and don't mask it beyond that?
   (you'll have to move xIP[cause]and and sIE[cause] above that then.)

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +        andi    T2, T5, INT_CAUSE_MSK           // clr INT & unarched arched bits (**NOTE expand if future extns use them)
The defined causes have been increase, so NUM_SPECED_EXCPT_CAUSES should be 19, and EXCPT_CAUSE_MASK should be ((1<<5)-1) on line 163

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +        sll     T4, T4, 17                      // Shift xxIE by 17
make this bit 24 after chgs above

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +        sll     T4, T4, 18                      // Shift xxIP by 18
make this bit 25 after chgs above. The go fix the diagram above to match

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/env/arch_test.h
> +// the mtrap_sigptr: label to separate normal and t
restore comment and add "signatures" afterward

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-SOFTWARE-INTR.S
> +		main:
This is probably true for all tests: I think you want to insert noops after any CSR write that might enable a trap to be taken, regardless of its supposed to or not. If you don't do that, the trap handler will cause instructions to be skipped when the trap is taken. ( won't comment on this again...)

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +			csrrs x0, CSR_MSTATUS, t0
This will trap... twice (on the mret of the first trap, it will immediately trap again with the other interrupt).
The trap handler will therefor advance the return address twice, and therefore at least two instructions after the instruction that causes the interrupt (the CSRRS) will be skipped. So, you need at least 2 noops after that instruction for this to work properly. I would put noops after every CSR write that might possibly cause a trap to be recognized, and maybe more.

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +// - Simultaneously generate a software interrupt and a timer interrupt
In general: SW and Timer interrupts are not guaranteed to see their respective interrupt pending bits immediately.
The MTIP/MSIP bits make take an unknown, but bounded time to be set after writing to the MMIO mtime/mtimecmp/swi_base addresses.

So, for this to work as expected, you must read and verify that the IP bits have been set before writing the global mstatus.mie bit (and loop polling for it if not), 
Or you can put a J .+0 infinite loop immediately after the setting of mstatus.mie. Then, when the trap is taken, it will skip [out of] the infinite loop upon returning, (so the infinite loop may never loop at all if the interrupt happens immediately, or it may happen after some arbitrary number of loops) This needs to be fixed in EVERY test. You can do something tricky by doing both, initializing a link register with an AUIPC, and using JAL .+0 as the infinite loop, followed by a store of (a relocated version of) the link register into the signature  after a noop or two. This will let you determine if it trapped immediately or not after polling showed that the IP bits were set
That is a very good thing because the spec does require the test to interrupt immediately after mtip, mie, and mtip are all set. You need to worry about this bounded delay in every test, so always check the IP bit before enabling the interrupt (unless you only use the infinite loop, in which case you don't care)

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-TIMER-INTR.S
> +			csrrs a4, CSR_MIP, x0
The spec says: MTIP is read-only in the mip register, and is cleared by writing to the memory-mapped
machine-mode timer compare register.MSIP is read-only in mip, and is written by accesses to memory-mapped control registers, which are used by remote harts to provide machine-level interprocessor interrupts, so this doesn't work. You should define and use the model specific RVMODEL_CLR_xTIMER_INT and RVMODEL_CLR_xSW_INT macros (where x is the mode) For setting them, use the SET versions of these (and do this in every tests)

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-TIMER-INTR.S
> +			csrrs a4, CSR_MIP, x0
note that there is no guarantee that MTIME won't increment before you set MIP, so it won't be equal (unlikely in fact)

2025-05-09 06:29 UTC, allenjbaum commented on coverage/m_interrupts/rv32_m_interrupts.cgf
> +      '(call_type != "interrupt") and ((mstatus & ${MSTATUS_MIE}) == 0) and ((mip & ${MIP_MSIP}) == 0)' : 0 # Validates software interrupt clearing mechanism when writing 0 to memory-mapped MSIP cont
This one will get  hit right out of reset. This needs to be conditioned on the old value of MIP_MSIP

2025-05-09 06:29 UTC, allenjbaum commented on coverage/m_interrupts/rv32_m_interrupts.cgf
> +      '(call_type != "interrupt") and ((mstatus & ${MSTATUS_MIE}) == 0) and ((mip & ${MIP_MTIP}) == 0)' : 0 # Checks MTIP bit clearing mechanism when no interrupt is being processed.
I think this will generate false positives unless you can check for edges rather than levels, i.e. mip=MTIP and old_mip!=MTIP

2025-05-09 06:29 UTC, allenjbaum commented on coverage/m_interrupts/rv32_m_interrupts.cgf
> +      '(call_type != "interrupt") and ((mstatus & ${MSTATUS_MIE}) == 0) and ((mie & ${MIE_MSIE}) == ${MIE_MSIE}) and ((mip & ${MIP_MSIP}) == ${MIP_MSIP})' : 0 # Confirms that no software interrupt is
Anytime you are checking for call_type != "interrupt" you'll get false positives; but edge checking in all of them.

2025-05-09 06:29 UTC, allenjbaum commented on coverage/m_interrupts/rv32_m_interrupts.cgf
> +      '(call_type == "interrupt") and ((mstatus & ${MSTATUS_MPP}) == ${MSTATUS_MPP_M}) and ((mstatus & ${MSTATUS_MPIE}) == ${MSTATUS_MPIE}) and ((mstatus & ${MSTATUS_MIE}) == 0) and ((mcause & ${INTE
Is this testing only trapping from Mmode? Don't we also want to test from Umode and Smode? Pretty tricky because you wo't necessarily have access to Mmode registers.

2025-05-09 06:29 UTC, allenjbaum commented on riscof-plugins/rv32/sail_cSim/env/model_test.h
> +#define RVMODEL_SET_MSW_INT             ;\
The RVMODEL_Set/Clr_M/H/Sxxx_INT macros need to be redefined so that the aren't placed inline, but are called as simple subroutines with a JAL, and return to the test with a JR. The should be instantiated (not defined) in  model_test.h as they are #defined, but with the name as a label at the start (instead of #define), and a JR at the end with a fixed link register (that tests will have to accomodate).

2025-05-09 06:29 UTC, allenjbaum commented on riscv-test-suite/rv32i_m/m_interrupts_32/src/CHK-M-INTR-PRIORITY.S
> +			csrrs x0, CSR_MSTATUS, t0
Actually, the skipping behavior might be exceptions only; need to check on that & see if we want to maintain skipping behavior

2026-02-24 16:38 UTC, jamesbeyond commented
ACT repository have been updated `act4` as the default branch, if you would like to contribute this PR to ACT4, we will need to ask you to review and update this PR, according to [guidelines](https://github.com/riscv-non-isa/riscv-arch-test/blob/act4/docs/DeveloperGuide.md) on the `act4` branch. For now, we have to close this PR. Thanks!

2026-02-24 16:38 UTC, closed without merging